(pick ball1 rooma left)
(move rooma roomb)
(drop ball1 roomb left)
(move roomb rooma)
(pick ball10 rooma left)
(move rooma roomb)
(drop ball10 roomb left)
(move roomb rooma)
(pick ball100 rooma left)
(move rooma roomb)
(drop ball100 roomb left)
(move roomb rooma)
(pick ball1000 rooma left)
(move rooma roomb)
(drop ball1000 roomb left)
(move roomb rooma)
(pick ball1001 rooma left)
(move rooma roomb)
(drop ball1001 roomb left)
(move roomb rooma)
(pick ball1002 rooma left)
(move rooma roomb)
(drop ball1002 roomb left)
(move roomb rooma)
(pick ball1003 rooma left)
(move rooma roomb)
(drop ball1003 roomb left)
(move roomb rooma)
(pick ball1004 rooma left)
(move rooma roomb)
(drop ball1004 roomb left)
(move roomb rooma)
(pick ball1005 rooma right)
(move rooma roomb)
(drop ball1005 roomb right)
(move roomb rooma)
(pick ball101 rooma left)
(move rooma roomb)
(drop ball101 roomb left)
(move roomb rooma)
(pick ball102 rooma left)
(move rooma roomb)
(drop ball102 roomb left)
(move roomb rooma)
(pick ball103 rooma left)
(move rooma roomb)
(drop ball103 roomb left)
(move roomb rooma)
(pick ball104 rooma left)
(move rooma roomb)
(drop ball104 roomb left)
(move roomb rooma)
(pick ball105 rooma left)
(move rooma roomb)
(drop ball105 roomb left)
(move roomb rooma)
(pick ball106 rooma left)
(move rooma roomb)
(drop ball106 roomb left)
(move roomb rooma)
(pick ball107 rooma left)
(move rooma roomb)
(drop ball107 roomb left)
(move roomb rooma)
(pick ball108 rooma left)
(move rooma roomb)
(drop ball108 roomb left)
(move roomb rooma)
(pick ball109 rooma left)
(move rooma roomb)
(drop ball109 roomb left)
(move roomb rooma)
(pick ball11 rooma left)
(move rooma roomb)
(drop ball11 roomb left)
(move roomb rooma)
(pick ball110 rooma left)
(move rooma roomb)
(drop ball110 roomb left)
(move roomb rooma)
(pick ball111 rooma left)
(move rooma roomb)
(drop ball111 roomb left)
(move roomb rooma)
(pick ball112 rooma left)
(move rooma roomb)
(drop ball112 roomb left)
(move roomb rooma)
(pick ball113 rooma left)
(move rooma roomb)
(drop ball113 roomb left)
(move roomb rooma)
(pick ball114 rooma left)
(move rooma roomb)
(drop ball114 roomb left)
(move roomb rooma)
(pick ball115 rooma left)
(move rooma roomb)
(drop ball115 roomb left)
(move roomb rooma)
(pick ball116 rooma left)
(move rooma roomb)
(drop ball116 roomb left)
(move roomb rooma)
(pick ball117 rooma left)
(move rooma roomb)
(drop ball117 roomb left)
(move roomb rooma)
(pick ball118 rooma left)
(move rooma roomb)
(drop ball118 roomb left)
(move roomb rooma)
(pick ball119 rooma left)
(move rooma roomb)
(drop ball119 roomb left)
(move roomb rooma)
(pick ball12 rooma left)
(move rooma roomb)
(drop ball12 roomb left)
(move roomb rooma)
(pick ball120 rooma left)
(move rooma roomb)
(drop ball120 roomb left)
(move roomb rooma)
(pick ball121 rooma left)
(move rooma roomb)
(drop ball121 roomb left)
(move roomb rooma)
(pick ball122 rooma left)
(move rooma roomb)
(drop ball122 roomb left)
(move roomb rooma)
(pick ball123 rooma left)
(move rooma roomb)
(drop ball123 roomb left)
(move roomb rooma)
(pick ball124 rooma left)
(move rooma roomb)
(drop ball124 roomb left)
(move roomb rooma)
(pick ball125 rooma left)
(move rooma roomb)
(drop ball125 roomb left)
(move roomb rooma)
(pick ball126 rooma left)
(move rooma roomb)
(drop ball126 roomb left)
(move roomb rooma)
(pick ball127 rooma left)
(move rooma roomb)
(drop ball127 roomb left)
(move roomb rooma)
(pick ball128 rooma left)
(move rooma roomb)
(drop ball128 roomb left)
(move roomb rooma)
(pick ball129 rooma left)
(move rooma roomb)
(drop ball129 roomb left)
(move roomb rooma)
(pick ball13 rooma left)
(move rooma roomb)
(drop ball13 roomb left)
(move roomb rooma)
(pick ball130 rooma left)
(move rooma roomb)
(drop ball130 roomb left)
(move roomb rooma)
(pick ball131 rooma left)
(move rooma roomb)
(drop ball131 roomb left)
(move roomb rooma)
(pick ball132 rooma left)
(move rooma roomb)
(drop ball132 roomb left)
(move roomb rooma)
(pick ball133 rooma left)
(move rooma roomb)
(drop ball133 roomb left)
(move roomb rooma)
(pick ball134 rooma left)
(move rooma roomb)
(drop ball134 roomb left)
(move roomb rooma)
(pick ball135 rooma left)
(move rooma roomb)
(drop ball135 roomb left)
(move roomb rooma)
(pick ball136 rooma left)
(move rooma roomb)
(drop ball136 roomb left)
(move roomb rooma)
(pick ball137 rooma left)
(move rooma roomb)
(drop ball137 roomb left)
(move roomb rooma)
(pick ball138 rooma left)
(move rooma roomb)
(drop ball138 roomb left)
(move roomb rooma)
(pick ball139 rooma left)
(move rooma roomb)
(drop ball139 roomb left)
(move roomb rooma)
(pick ball14 rooma left)
(move rooma roomb)
(drop ball14 roomb left)
(move roomb rooma)
(pick ball140 rooma left)
(move rooma roomb)
(drop ball140 roomb left)
(move roomb rooma)
(pick ball141 rooma left)
(move rooma roomb)
(drop ball141 roomb left)
(move roomb rooma)
(pick ball142 rooma left)
(move rooma roomb)
(drop ball142 roomb left)
(move roomb rooma)
(pick ball143 rooma left)
(move rooma roomb)
(drop ball143 roomb left)
(move roomb rooma)
(pick ball144 rooma left)
(move rooma roomb)
(drop ball144 roomb left)
(move roomb rooma)
(pick ball145 rooma left)
(move rooma roomb)
(drop ball145 roomb left)
(move roomb rooma)
(pick ball146 rooma left)
(move rooma roomb)
(drop ball146 roomb left)
(move roomb rooma)
(pick ball147 rooma left)
(move rooma roomb)
(drop ball147 roomb left)
(move roomb rooma)
(pick ball148 rooma left)
(move rooma roomb)
(drop ball148 roomb left)
(move roomb rooma)
(pick ball149 rooma left)
(move rooma roomb)
(drop ball149 roomb left)
(move roomb rooma)
(pick ball15 rooma left)
(move rooma roomb)
(drop ball15 roomb left)
(move roomb rooma)
(pick ball150 rooma left)
(move rooma roomb)
(drop ball150 roomb left)
(move roomb rooma)
(pick ball151 rooma left)
(move rooma roomb)
(drop ball151 roomb left)
(move roomb rooma)
(pick ball152 rooma right)
(move rooma roomb)
(drop ball152 roomb right)
(move roomb rooma)
(pick ball153 rooma left)
(move rooma roomb)
(drop ball153 roomb left)
(move roomb rooma)
(pick ball154 rooma left)
(move rooma roomb)
(drop ball154 roomb left)
(move roomb rooma)
(pick ball155 rooma left)
(move rooma roomb)
(drop ball155 roomb left)
(move roomb rooma)
(pick ball156 rooma left)
(move rooma roomb)
(drop ball156 roomb left)
(move roomb rooma)
(pick ball157 rooma left)
(move rooma roomb)
(drop ball157 roomb left)
(move roomb rooma)
(pick ball158 rooma left)
(move rooma roomb)
(drop ball158 roomb left)
(move roomb rooma)
(pick ball159 rooma left)
(move rooma roomb)
(drop ball159 roomb left)
(move roomb rooma)
(pick ball16 rooma left)
(move rooma roomb)
(drop ball16 roomb left)
(move roomb rooma)
(pick ball160 rooma left)
(move rooma roomb)
(drop ball160 roomb left)
(move roomb rooma)
(pick ball161 rooma left)
(move rooma roomb)
(drop ball161 roomb left)
(move roomb rooma)
(pick ball162 rooma left)
(move rooma roomb)
(drop ball162 roomb left)
(move roomb rooma)
(pick ball163 rooma left)
(move rooma roomb)
(drop ball163 roomb left)
(move roomb rooma)
(pick ball164 rooma left)
(move rooma roomb)
(drop ball164 roomb left)
(move roomb rooma)
(pick ball165 rooma left)
(move rooma roomb)
(drop ball165 roomb left)
(move roomb rooma)
(pick ball166 rooma left)
(move rooma roomb)
(drop ball166 roomb left)
(move roomb rooma)
(pick ball167 rooma left)
(move rooma roomb)
(drop ball167 roomb left)
(move roomb rooma)
(pick ball168 rooma left)
(move rooma roomb)
(drop ball168 roomb left)
(move roomb rooma)
(pick ball169 rooma left)
(move rooma roomb)
(drop ball169 roomb left)
(move roomb rooma)
(pick ball17 rooma left)
(move rooma roomb)
(drop ball17 roomb left)
(move roomb rooma)
(pick ball170 rooma left)
(move rooma roomb)
(drop ball170 roomb left)
(move roomb rooma)
(pick ball171 rooma left)
(move rooma roomb)
(drop ball171 roomb left)
(move roomb rooma)
(pick ball172 rooma left)
(move rooma roomb)
(drop ball172 roomb left)
(move roomb rooma)
(pick ball173 rooma left)
(move rooma roomb)
(drop ball173 roomb left)
(move roomb rooma)
(pick ball174 rooma left)
(move rooma roomb)
(drop ball174 roomb left)
(move roomb rooma)
(pick ball175 rooma left)
(move rooma roomb)
(drop ball175 roomb left)
(move roomb rooma)
(pick ball176 rooma left)
(move rooma roomb)
(drop ball176 roomb left)
(move roomb rooma)
(pick ball177 rooma left)
(move rooma roomb)
(drop ball177 roomb left)
(move roomb rooma)
(pick ball178 rooma left)
(move rooma roomb)
(drop ball178 roomb left)
(move roomb rooma)
(pick ball179 rooma left)
(move rooma roomb)
(drop ball179 roomb left)
(move roomb rooma)
(pick ball18 rooma left)
(move rooma roomb)
(drop ball18 roomb left)
(move roomb rooma)
(pick ball180 rooma left)
(move rooma roomb)
(drop ball180 roomb left)
(move roomb rooma)
(pick ball181 rooma left)
(move rooma roomb)
(drop ball181 roomb left)
(move roomb rooma)
(pick ball182 rooma left)
(move rooma roomb)
(drop ball182 roomb left)
(move roomb rooma)
(pick ball183 rooma left)
(move rooma roomb)
(drop ball183 roomb left)
(move roomb rooma)
(pick ball184 rooma left)
(move rooma roomb)
(drop ball184 roomb left)
(move roomb rooma)
(pick ball185 rooma left)
(move rooma roomb)
(drop ball185 roomb left)
(move roomb rooma)
(pick ball186 rooma left)
(move rooma roomb)
(drop ball186 roomb left)
(move roomb rooma)
(pick ball187 rooma left)
(move rooma roomb)
(drop ball187 roomb left)
(move roomb rooma)
(pick ball188 rooma left)
(move rooma roomb)
(drop ball188 roomb left)
(move roomb rooma)
(pick ball189 rooma left)
(move rooma roomb)
(drop ball189 roomb left)
(move roomb rooma)
(pick ball19 rooma left)
(move rooma roomb)
(drop ball19 roomb left)
(move roomb rooma)
(pick ball190 rooma left)
(move rooma roomb)
(drop ball190 roomb left)
(move roomb rooma)
(pick ball191 rooma left)
(move rooma roomb)
(drop ball191 roomb left)
(move roomb rooma)
(pick ball192 rooma left)
(move rooma roomb)
(drop ball192 roomb left)
(move roomb rooma)
(pick ball193 rooma left)
(move rooma roomb)
(drop ball193 roomb left)
(move roomb rooma)
(pick ball194 rooma left)
(move rooma roomb)
(drop ball194 roomb left)
(move roomb rooma)
(pick ball195 rooma left)
(move rooma roomb)
(drop ball195 roomb left)
(move roomb rooma)
(pick ball196 rooma left)
(move rooma roomb)
(drop ball196 roomb left)
(move roomb rooma)
(pick ball197 rooma left)
(move rooma roomb)
(drop ball197 roomb left)
(move roomb rooma)
(pick ball198 rooma left)
(move rooma roomb)
(drop ball198 roomb left)
(move roomb rooma)
(pick ball199 rooma left)
(move rooma roomb)
(drop ball199 roomb left)
(move roomb rooma)
(pick ball2 rooma left)
(move rooma roomb)
(drop ball2 roomb left)
(move roomb rooma)
(pick ball20 rooma left)
(move rooma roomb)
(drop ball20 roomb left)
(move roomb rooma)
(pick ball200 rooma left)
(move rooma roomb)
(drop ball200 roomb left)
(move roomb rooma)
(pick ball201 rooma left)
(move rooma roomb)
(drop ball201 roomb left)
(move roomb rooma)
(pick ball202 rooma right)
(move rooma roomb)
(drop ball202 roomb right)
(move roomb rooma)
(pick ball203 rooma left)
(move rooma roomb)
(drop ball203 roomb left)
(move roomb rooma)
(pick ball204 rooma left)
(move rooma roomb)
(drop ball204 roomb left)
(move roomb rooma)
(pick ball205 rooma left)
(move rooma roomb)
(drop ball205 roomb left)
(move roomb rooma)
(pick ball206 rooma left)
(move rooma roomb)
(drop ball206 roomb left)
(move roomb rooma)
(pick ball207 rooma left)
(move rooma roomb)
(drop ball207 roomb left)
(move roomb rooma)
(pick ball208 rooma left)
(move rooma roomb)
(drop ball208 roomb left)
(move roomb rooma)
(pick ball209 rooma left)
(move rooma roomb)
(drop ball209 roomb left)
(move roomb rooma)
(pick ball21 rooma left)
(move rooma roomb)
(drop ball21 roomb left)
(move roomb rooma)
(pick ball210 rooma left)
(move rooma roomb)
(drop ball210 roomb left)
(move roomb rooma)
(pick ball211 rooma left)
(move rooma roomb)
(drop ball211 roomb left)
(move roomb rooma)
(pick ball212 rooma left)
(move rooma roomb)
(drop ball212 roomb left)
(move roomb rooma)
(pick ball213 rooma left)
(move rooma roomb)
(drop ball213 roomb left)
(move roomb rooma)
(pick ball214 rooma left)
(move rooma roomb)
(drop ball214 roomb left)
(move roomb rooma)
(pick ball215 rooma left)
(move rooma roomb)
(drop ball215 roomb left)
(move roomb rooma)
(pick ball216 rooma left)
(move rooma roomb)
(drop ball216 roomb left)
(move roomb rooma)
(pick ball217 rooma left)
(move rooma roomb)
(drop ball217 roomb left)
(move roomb rooma)
(pick ball218 rooma left)
(move rooma roomb)
(drop ball218 roomb left)
(move roomb rooma)
(pick ball219 rooma left)
(move rooma roomb)
(drop ball219 roomb left)
(move roomb rooma)
(pick ball22 rooma left)
(move rooma roomb)
(drop ball22 roomb left)
(move roomb rooma)
(pick ball220 rooma left)
(move rooma roomb)
(drop ball220 roomb left)
(move roomb rooma)
(pick ball221 rooma left)
(move rooma roomb)
(drop ball221 roomb left)
(move roomb rooma)
(pick ball222 rooma left)
(move rooma roomb)
(drop ball222 roomb left)
(move roomb rooma)
(pick ball223 rooma left)
(move rooma roomb)
(drop ball223 roomb left)
(move roomb rooma)
(pick ball224 rooma left)
(move rooma roomb)
(drop ball224 roomb left)
(move roomb rooma)
(pick ball225 rooma left)
(move rooma roomb)
(drop ball225 roomb left)
(move roomb rooma)
(pick ball226 rooma left)
(move rooma roomb)
(drop ball226 roomb left)
(move roomb rooma)
(pick ball227 rooma left)
(move rooma roomb)
(drop ball227 roomb left)
(move roomb rooma)
(pick ball228 rooma left)
(move rooma roomb)
(drop ball228 roomb left)
(move roomb rooma)
(pick ball229 rooma left)
(move rooma roomb)
(drop ball229 roomb left)
(move roomb rooma)
(pick ball23 rooma left)
(move rooma roomb)
(drop ball23 roomb left)
(move roomb rooma)
(pick ball230 rooma left)
(move rooma roomb)
(drop ball230 roomb left)
(move roomb rooma)
(pick ball231 rooma left)
(move rooma roomb)
(drop ball231 roomb left)
(move roomb rooma)
(pick ball232 rooma left)
(move rooma roomb)
(drop ball232 roomb left)
(move roomb rooma)
(pick ball233 rooma left)
(move rooma roomb)
(drop ball233 roomb left)
(move roomb rooma)
(pick ball234 rooma left)
(move rooma roomb)
(drop ball234 roomb left)
(move roomb rooma)
(pick ball235 rooma left)
(move rooma roomb)
(drop ball235 roomb left)
(move roomb rooma)
(pick ball236 rooma left)
(move rooma roomb)
(drop ball236 roomb left)
(move roomb rooma)
(pick ball237 rooma left)
(move rooma roomb)
(drop ball237 roomb left)
(move roomb rooma)
(pick ball238 rooma left)
(move rooma roomb)
(drop ball238 roomb left)
(move roomb rooma)
(pick ball239 rooma left)
(move rooma roomb)
(drop ball239 roomb left)
(move roomb rooma)
(pick ball24 rooma left)
(move rooma roomb)
(drop ball24 roomb left)
(move roomb rooma)
(pick ball240 rooma left)
(move rooma roomb)
(drop ball240 roomb left)
(move roomb rooma)
(pick ball241 rooma left)
(move rooma roomb)
(drop ball241 roomb left)
(move roomb rooma)
(pick ball242 rooma left)
(move rooma roomb)
(drop ball242 roomb left)
(move roomb rooma)
(pick ball243 rooma left)
(move rooma roomb)
(drop ball243 roomb left)
(move roomb rooma)
(pick ball244 rooma left)
(move rooma roomb)
(drop ball244 roomb left)
(move roomb rooma)
(pick ball245 rooma left)
(move rooma roomb)
(drop ball245 roomb left)
(move roomb rooma)
(pick ball246 rooma left)
(move rooma roomb)
(drop ball246 roomb left)
(move roomb rooma)
(pick ball247 rooma left)
(move rooma roomb)
(drop ball247 roomb left)
(move roomb rooma)
(pick ball248 rooma left)
(move rooma roomb)
(drop ball248 roomb left)
(move roomb rooma)
(pick ball249 rooma left)
(move rooma roomb)
(drop ball249 roomb left)
(move roomb rooma)
(pick ball25 rooma left)
(move rooma roomb)
(drop ball25 roomb left)
(move roomb rooma)
(pick ball250 rooma left)
(move rooma roomb)
(drop ball250 roomb left)
(move roomb rooma)
(pick ball251 rooma left)
(move rooma roomb)
(drop ball251 roomb left)
(move roomb rooma)
(pick ball252 rooma left)
(move rooma roomb)
(drop ball252 roomb left)
(move roomb rooma)
(pick ball253 rooma left)
(move rooma roomb)
(drop ball253 roomb left)
(move roomb rooma)
(pick ball254 rooma right)
(move rooma roomb)
(drop ball254 roomb right)
(move roomb rooma)
(pick ball255 rooma left)
(move rooma roomb)
(drop ball255 roomb left)
(move roomb rooma)
(pick ball256 rooma left)
(move rooma roomb)
(drop ball256 roomb left)
(move roomb rooma)
(pick ball257 rooma left)
(move rooma roomb)
(drop ball257 roomb left)
(move roomb rooma)
(pick ball258 rooma left)
(move rooma roomb)
(drop ball258 roomb left)
(move roomb rooma)
(pick ball259 rooma left)
(move rooma roomb)
(drop ball259 roomb left)
(move roomb rooma)
(pick ball26 rooma left)
(move rooma roomb)
(drop ball26 roomb left)
(move roomb rooma)
(pick ball260 rooma left)
(move rooma roomb)
(drop ball260 roomb left)
(move roomb rooma)
(pick ball261 rooma left)
(move rooma roomb)
(drop ball261 roomb left)
(move roomb rooma)
(pick ball262 rooma left)
(move rooma roomb)
(drop ball262 roomb left)
(move roomb rooma)
(pick ball263 rooma left)
(move rooma roomb)
(drop ball263 roomb left)
(move roomb rooma)
(pick ball264 rooma left)
(move rooma roomb)
(drop ball264 roomb left)
(move roomb rooma)
(pick ball265 rooma left)
(move rooma roomb)
(drop ball265 roomb left)
(move roomb rooma)
(pick ball266 rooma left)
(move rooma roomb)
(drop ball266 roomb left)
(move roomb rooma)
(pick ball267 rooma left)
(move rooma roomb)
(drop ball267 roomb left)
(move roomb rooma)
(pick ball268 rooma left)
(move rooma roomb)
(drop ball268 roomb left)
(move roomb rooma)
(pick ball269 rooma left)
(move rooma roomb)
(drop ball269 roomb left)
(move roomb rooma)
(pick ball27 rooma left)
(move rooma roomb)
(drop ball27 roomb left)
(move roomb rooma)
(pick ball270 rooma left)
(move rooma roomb)
(drop ball270 roomb left)
(move roomb rooma)
(pick ball271 rooma left)
(move rooma roomb)
(drop ball271 roomb left)
(move roomb rooma)
(pick ball272 rooma left)
(move rooma roomb)
(drop ball272 roomb left)
(move roomb rooma)
(pick ball273 rooma left)
(move rooma roomb)
(drop ball273 roomb left)
(move roomb rooma)
(pick ball274 rooma left)
(move rooma roomb)
(drop ball274 roomb left)
(move roomb rooma)
(pick ball275 rooma left)
(move rooma roomb)
(drop ball275 roomb left)
(move roomb rooma)
(pick ball276 rooma left)
(move rooma roomb)
(drop ball276 roomb left)
(move roomb rooma)
(pick ball277 rooma left)
(move rooma roomb)
(drop ball277 roomb left)
(move roomb rooma)
(pick ball278 rooma left)
(move rooma roomb)
(drop ball278 roomb left)
(move roomb rooma)
(pick ball279 rooma left)
(move rooma roomb)
(drop ball279 roomb left)
(move roomb rooma)
(pick ball28 rooma left)
(move rooma roomb)
(drop ball28 roomb left)
(move roomb rooma)
(pick ball280 rooma left)
(move rooma roomb)
(drop ball280 roomb left)
(move roomb rooma)
(pick ball281 rooma left)
(move rooma roomb)
(drop ball281 roomb left)
(move roomb rooma)
(pick ball282 rooma left)
(move rooma roomb)
(drop ball282 roomb left)
(move roomb rooma)
(pick ball283 rooma left)
(move rooma roomb)
(drop ball283 roomb left)
(move roomb rooma)
(pick ball284 rooma left)
(move rooma roomb)
(drop ball284 roomb left)
(move roomb rooma)
(pick ball285 rooma left)
(move rooma roomb)
(drop ball285 roomb left)
(move roomb rooma)
(pick ball286 rooma left)
(move rooma roomb)
(drop ball286 roomb left)
(move roomb rooma)
(pick ball287 rooma left)
(move rooma roomb)
(drop ball287 roomb left)
(move roomb rooma)
(pick ball288 rooma left)
(move rooma roomb)
(drop ball288 roomb left)
(move roomb rooma)
(pick ball289 rooma left)
(move rooma roomb)
(drop ball289 roomb left)
(move roomb rooma)
(pick ball29 rooma left)
(move rooma roomb)
(drop ball29 roomb left)
(move roomb rooma)
(pick ball290 rooma left)
(move rooma roomb)
(drop ball290 roomb left)
(move roomb rooma)
(pick ball291 rooma left)
(move rooma roomb)
(drop ball291 roomb left)
(move roomb rooma)
(pick ball292 rooma left)
(move rooma roomb)
(drop ball292 roomb left)
(move roomb rooma)
(pick ball293 rooma left)
(move rooma roomb)
(drop ball293 roomb left)
(move roomb rooma)
(pick ball294 rooma left)
(move rooma roomb)
(drop ball294 roomb left)
(move roomb rooma)
(pick ball295 rooma left)
(move rooma roomb)
(drop ball295 roomb left)
(move roomb rooma)
(pick ball296 rooma left)
(move rooma roomb)
(drop ball296 roomb left)
(move roomb rooma)
(pick ball297 rooma left)
(move rooma roomb)
(drop ball297 roomb left)
(move roomb rooma)
(pick ball298 rooma left)
(move rooma roomb)
(drop ball298 roomb left)
(move roomb rooma)
(pick ball299 rooma left)
(move rooma roomb)
(drop ball299 roomb left)
(move roomb rooma)
(pick ball3 rooma left)
(move rooma roomb)
(drop ball3 roomb left)
(move roomb rooma)
(pick ball30 rooma left)
(move rooma roomb)
(drop ball30 roomb left)
(move roomb rooma)
(pick ball300 rooma left)
(move rooma roomb)
(drop ball300 roomb left)
(move roomb rooma)
(pick ball301 rooma left)
(move rooma roomb)
(drop ball301 roomb left)
(move roomb rooma)
(pick ball302 rooma left)
(move rooma roomb)
(drop ball302 roomb left)
(move roomb rooma)
(pick ball303 rooma left)
(move rooma roomb)
(drop ball303 roomb left)
(move roomb rooma)
(pick ball304 rooma left)
(move rooma roomb)
(drop ball304 roomb left)
(move roomb rooma)
(pick ball305 rooma right)
(move rooma roomb)
(drop ball305 roomb right)
(move roomb rooma)
(pick ball306 rooma left)
(move rooma roomb)
(drop ball306 roomb left)
(move roomb rooma)
(pick ball307 rooma left)
(move rooma roomb)
(drop ball307 roomb left)
(move roomb rooma)
(pick ball308 rooma left)
(move rooma roomb)
(drop ball308 roomb left)
(move roomb rooma)
(pick ball309 rooma left)
(move rooma roomb)
(drop ball309 roomb left)
(move roomb rooma)
(pick ball31 rooma left)
(move rooma roomb)
(drop ball31 roomb left)
(move roomb rooma)
(pick ball310 rooma left)
(move rooma roomb)
(drop ball310 roomb left)
(move roomb rooma)
(pick ball311 rooma left)
(move rooma roomb)
(drop ball311 roomb left)
(move roomb rooma)
(pick ball312 rooma left)
(move rooma roomb)
(drop ball312 roomb left)
(move roomb rooma)
(pick ball313 rooma left)
(move rooma roomb)
(drop ball313 roomb left)
(move roomb rooma)
(pick ball314 rooma left)
(move rooma roomb)
(drop ball314 roomb left)
(move roomb rooma)
(pick ball315 rooma left)
(move rooma roomb)
(drop ball315 roomb left)
(move roomb rooma)
(pick ball316 rooma left)
(move rooma roomb)
(drop ball316 roomb left)
(move roomb rooma)
(pick ball317 rooma left)
(move rooma roomb)
(drop ball317 roomb left)
(move roomb rooma)
(pick ball318 rooma left)
(move rooma roomb)
(drop ball318 roomb left)
(move roomb rooma)
(pick ball319 rooma left)
(move rooma roomb)
(drop ball319 roomb left)
(move roomb rooma)
(pick ball32 rooma left)
(move rooma roomb)
(drop ball32 roomb left)
(move roomb rooma)
(pick ball320 rooma left)
(move rooma roomb)
(drop ball320 roomb left)
(move roomb rooma)
(pick ball321 rooma left)
(move rooma roomb)
(drop ball321 roomb left)
(move roomb rooma)
(pick ball322 rooma left)
(move rooma roomb)
(drop ball322 roomb left)
(move roomb rooma)
(pick ball323 rooma left)
(move rooma roomb)
(drop ball323 roomb left)
(move roomb rooma)
(pick ball324 rooma left)
(move rooma roomb)
(drop ball324 roomb left)
(move roomb rooma)
(pick ball325 rooma left)
(move rooma roomb)
(drop ball325 roomb left)
(move roomb rooma)
(pick ball326 rooma left)
(move rooma roomb)
(drop ball326 roomb left)
(move roomb rooma)
(pick ball327 rooma left)
(move rooma roomb)
(drop ball327 roomb left)
(move roomb rooma)
(pick ball328 rooma left)
(move rooma roomb)
(drop ball328 roomb left)
(move roomb rooma)
(pick ball329 rooma left)
(move rooma roomb)
(drop ball329 roomb left)
(move roomb rooma)
(pick ball33 rooma left)
(move rooma roomb)
(drop ball33 roomb left)
(move roomb rooma)
(pick ball330 rooma left)
(move rooma roomb)
(drop ball330 roomb left)
(move roomb rooma)
(pick ball331 rooma left)
(move rooma roomb)
(drop ball331 roomb left)
(move roomb rooma)
(pick ball332 rooma left)
(move rooma roomb)
(drop ball332 roomb left)
(move roomb rooma)
(pick ball333 rooma left)
(move rooma roomb)
(drop ball333 roomb left)
(move roomb rooma)
(pick ball334 rooma left)
(move rooma roomb)
(drop ball334 roomb left)
(move roomb rooma)
(pick ball335 rooma left)
(move rooma roomb)
(drop ball335 roomb left)
(move roomb rooma)
(pick ball336 rooma left)
(move rooma roomb)
(drop ball336 roomb left)
(move roomb rooma)
(pick ball337 rooma left)
(move rooma roomb)
(drop ball337 roomb left)
(move roomb rooma)
(pick ball338 rooma left)
(move rooma roomb)
(drop ball338 roomb left)
(move roomb rooma)
(pick ball339 rooma left)
(move rooma roomb)
(drop ball339 roomb left)
(move roomb rooma)
(pick ball34 rooma left)
(move rooma roomb)
(drop ball34 roomb left)
(move roomb rooma)
(pick ball340 rooma left)
(move rooma roomb)
(drop ball340 roomb left)
(move roomb rooma)
(pick ball341 rooma left)
(move rooma roomb)
(drop ball341 roomb left)
(move roomb rooma)
(pick ball342 rooma left)
(move rooma roomb)
(drop ball342 roomb left)
(move roomb rooma)
(pick ball343 rooma left)
(move rooma roomb)
(drop ball343 roomb left)
(move roomb rooma)
(pick ball344 rooma left)
(move rooma roomb)
(drop ball344 roomb left)
(move roomb rooma)
(pick ball345 rooma left)
(move rooma roomb)
(drop ball345 roomb left)
(move roomb rooma)
(pick ball346 rooma left)
(move rooma roomb)
(drop ball346 roomb left)
(move roomb rooma)
(pick ball347 rooma left)
(move rooma roomb)
(drop ball347 roomb left)
(move roomb rooma)
(pick ball348 rooma left)
(move rooma roomb)
(drop ball348 roomb left)
(move roomb rooma)
(pick ball349 rooma left)
(move rooma roomb)
(drop ball349 roomb left)
(move roomb rooma)
(pick ball35 rooma left)
(move rooma roomb)
(drop ball35 roomb left)
(move roomb rooma)
(pick ball350 rooma left)
(move rooma roomb)
(drop ball350 roomb left)
(move roomb rooma)
(pick ball351 rooma left)
(move rooma roomb)
(drop ball351 roomb left)
(move roomb rooma)
(pick ball352 rooma left)
(move rooma roomb)
(drop ball352 roomb left)
(move roomb rooma)
(pick ball353 rooma left)
(move rooma roomb)
(drop ball353 roomb left)
(move roomb rooma)
(pick ball354 rooma left)
(move rooma roomb)
(drop ball354 roomb left)
(move roomb rooma)
(pick ball355 rooma left)
(move rooma roomb)
(drop ball355 roomb left)
(move roomb rooma)
(pick ball356 rooma right)
(move rooma roomb)
(drop ball356 roomb right)
(move roomb rooma)
(pick ball357 rooma left)
(move rooma roomb)
(drop ball357 roomb left)
(move roomb rooma)
(pick ball358 rooma left)
(move rooma roomb)
(drop ball358 roomb left)
(move roomb rooma)
(pick ball359 rooma left)
(move rooma roomb)
(drop ball359 roomb left)
(move roomb rooma)
(pick ball36 rooma left)
(move rooma roomb)
(drop ball36 roomb left)
(move roomb rooma)
(pick ball360 rooma left)
(move rooma roomb)
(drop ball360 roomb left)
(move roomb rooma)
(pick ball361 rooma left)
(move rooma roomb)
(drop ball361 roomb left)
(move roomb rooma)
(pick ball362 rooma left)
(move rooma roomb)
(drop ball362 roomb left)
(move roomb rooma)
(pick ball363 rooma left)
(move rooma roomb)
(drop ball363 roomb left)
(move roomb rooma)
(pick ball364 rooma left)
(move rooma roomb)
(drop ball364 roomb left)
(move roomb rooma)
(pick ball365 rooma left)
(move rooma roomb)
(drop ball365 roomb left)
(move roomb rooma)
(pick ball366 rooma left)
(move rooma roomb)
(drop ball366 roomb left)
(move roomb rooma)
(pick ball367 rooma left)
(move rooma roomb)
(drop ball367 roomb left)
(move roomb rooma)
(pick ball368 rooma left)
(move rooma roomb)
(drop ball368 roomb left)
(move roomb rooma)
(pick ball369 rooma left)
(move rooma roomb)
(drop ball369 roomb left)
(move roomb rooma)
(pick ball37 rooma left)
(move rooma roomb)
(drop ball37 roomb left)
(move roomb rooma)
(pick ball370 rooma left)
(move rooma roomb)
(drop ball370 roomb left)
(move roomb rooma)
(pick ball371 rooma left)
(move rooma roomb)
(drop ball371 roomb left)
(move roomb rooma)
(pick ball372 rooma left)
(move rooma roomb)
(drop ball372 roomb left)
(move roomb rooma)
(pick ball373 rooma left)
(move rooma roomb)
(drop ball373 roomb left)
(move roomb rooma)
(pick ball374 rooma left)
(move rooma roomb)
(drop ball374 roomb left)
(move roomb rooma)
(pick ball375 rooma left)
(move rooma roomb)
(drop ball375 roomb left)
(move roomb rooma)
(pick ball376 rooma left)
(move rooma roomb)
(drop ball376 roomb left)
(move roomb rooma)
(pick ball377 rooma left)
(move rooma roomb)
(drop ball377 roomb left)
(move roomb rooma)
(pick ball378 rooma left)
(move rooma roomb)
(drop ball378 roomb left)
(move roomb rooma)
(pick ball379 rooma left)
(move rooma roomb)
(drop ball379 roomb left)
(move roomb rooma)
(pick ball38 rooma left)
(move rooma roomb)
(drop ball38 roomb left)
(move roomb rooma)
(pick ball380 rooma left)
(move rooma roomb)
(drop ball380 roomb left)
(move roomb rooma)
(pick ball381 rooma left)
(move rooma roomb)
(drop ball381 roomb left)
(move roomb rooma)
(pick ball382 rooma left)
(move rooma roomb)
(drop ball382 roomb left)
(move roomb rooma)
(pick ball383 rooma left)
(move rooma roomb)
(drop ball383 roomb left)
(move roomb rooma)
(pick ball384 rooma left)
(move rooma roomb)
(drop ball384 roomb left)
(move roomb rooma)
(pick ball385 rooma left)
(move rooma roomb)
(drop ball385 roomb left)
(move roomb rooma)
(pick ball386 rooma left)
(move rooma roomb)
(drop ball386 roomb left)
(move roomb rooma)
(pick ball387 rooma left)
(move rooma roomb)
(drop ball387 roomb left)
(move roomb rooma)
(pick ball388 rooma left)
(move rooma roomb)
(drop ball388 roomb left)
(move roomb rooma)
(pick ball389 rooma left)
(move rooma roomb)
(drop ball389 roomb left)
(move roomb rooma)
(pick ball39 rooma left)
(move rooma roomb)
(drop ball39 roomb left)
(move roomb rooma)
(pick ball390 rooma left)
(move rooma roomb)
(drop ball390 roomb left)
(move roomb rooma)
(pick ball391 rooma left)
(move rooma roomb)
(drop ball391 roomb left)
(move roomb rooma)
(pick ball392 rooma left)
(move rooma roomb)
(drop ball392 roomb left)
(move roomb rooma)
(pick ball393 rooma left)
(move rooma roomb)
(drop ball393 roomb left)
(move roomb rooma)
(pick ball394 rooma left)
(move rooma roomb)
(drop ball394 roomb left)
(move roomb rooma)
(pick ball395 rooma left)
(move rooma roomb)
(drop ball395 roomb left)
(move roomb rooma)
(pick ball396 rooma left)
(move rooma roomb)
(drop ball396 roomb left)
(move roomb rooma)
(pick ball397 rooma left)
(move rooma roomb)
(drop ball397 roomb left)
(move roomb rooma)
(pick ball398 rooma left)
(move rooma roomb)
(drop ball398 roomb left)
(move roomb rooma)
(pick ball399 rooma left)
(move rooma roomb)
(drop ball399 roomb left)
(move roomb rooma)
(pick ball4 rooma left)
(move rooma roomb)
(drop ball4 roomb left)
(move roomb rooma)
(pick ball40 rooma left)
(move rooma roomb)
(drop ball40 roomb left)
(move roomb rooma)
(pick ball400 rooma left)
(move rooma roomb)
(drop ball400 roomb left)
(move roomb rooma)
(pick ball401 rooma left)
(move rooma roomb)
(drop ball401 roomb left)
(move roomb rooma)
(pick ball402 rooma left)
(move rooma roomb)
(drop ball402 roomb left)
(move roomb rooma)
(pick ball403 rooma left)
(move rooma roomb)
(drop ball403 roomb left)
(move roomb rooma)
(pick ball404 rooma left)
(move rooma roomb)
(drop ball404 roomb left)
(move roomb rooma)
(pick ball405 rooma left)
(move rooma roomb)
(drop ball405 roomb left)
(move roomb rooma)
(pick ball406 rooma left)
(move rooma roomb)
(drop ball406 roomb left)
(move roomb rooma)
(pick ball407 rooma right)
(move rooma roomb)
(drop ball407 roomb right)
(move roomb rooma)
(pick ball408 rooma left)
(move rooma roomb)
(drop ball408 roomb left)
(move roomb rooma)
(pick ball409 rooma left)
(move rooma roomb)
(drop ball409 roomb left)
(move roomb rooma)
(pick ball41 rooma left)
(move rooma roomb)
(drop ball41 roomb left)
(move roomb rooma)
(pick ball410 rooma left)
(move rooma roomb)
(drop ball410 roomb left)
(move roomb rooma)
(pick ball411 rooma left)
(move rooma roomb)
(drop ball411 roomb left)
(move roomb rooma)
(pick ball412 rooma left)
(move rooma roomb)
(drop ball412 roomb left)
(move roomb rooma)
(pick ball413 rooma left)
(move rooma roomb)
(drop ball413 roomb left)
(move roomb rooma)
(pick ball414 rooma left)
(move rooma roomb)
(drop ball414 roomb left)
(move roomb rooma)
(pick ball415 rooma left)
(move rooma roomb)
(drop ball415 roomb left)
(move roomb rooma)
(pick ball416 rooma left)
(move rooma roomb)
(drop ball416 roomb left)
(move roomb rooma)
(pick ball417 rooma left)
(move rooma roomb)
(drop ball417 roomb left)
(move roomb rooma)
(pick ball418 rooma left)
(move rooma roomb)
(drop ball418 roomb left)
(move roomb rooma)
(pick ball419 rooma left)
(move rooma roomb)
(drop ball419 roomb left)
(move roomb rooma)
(pick ball42 rooma left)
(move rooma roomb)
(drop ball42 roomb left)
(move roomb rooma)
(pick ball420 rooma left)
(move rooma roomb)
(drop ball420 roomb left)
(move roomb rooma)
(pick ball421 rooma left)
(move rooma roomb)
(drop ball421 roomb left)
(move roomb rooma)
(pick ball422 rooma left)
(move rooma roomb)
(drop ball422 roomb left)
(move roomb rooma)
(pick ball423 rooma left)
(move rooma roomb)
(drop ball423 roomb left)
(move roomb rooma)
(pick ball424 rooma left)
(move rooma roomb)
(drop ball424 roomb left)
(move roomb rooma)
(pick ball425 rooma left)
(move rooma roomb)
(drop ball425 roomb left)
(move roomb rooma)
(pick ball426 rooma left)
(move rooma roomb)
(drop ball426 roomb left)
(move roomb rooma)
(pick ball427 rooma left)
(move rooma roomb)
(drop ball427 roomb left)
(move roomb rooma)
(pick ball428 rooma left)
(move rooma roomb)
(drop ball428 roomb left)
(move roomb rooma)
(pick ball429 rooma left)
(move rooma roomb)
(drop ball429 roomb left)
(move roomb rooma)
(pick ball43 rooma left)
(move rooma roomb)
(drop ball43 roomb left)
(move roomb rooma)
(pick ball430 rooma left)
(move rooma roomb)
(drop ball430 roomb left)
(move roomb rooma)
(pick ball431 rooma left)
(move rooma roomb)
(drop ball431 roomb left)
(move roomb rooma)
(pick ball432 rooma left)
(move rooma roomb)
(drop ball432 roomb left)
(move roomb rooma)
(pick ball433 rooma left)
(move rooma roomb)
(drop ball433 roomb left)
(move roomb rooma)
(pick ball434 rooma left)
(move rooma roomb)
(drop ball434 roomb left)
(move roomb rooma)
(pick ball435 rooma left)
(move rooma roomb)
(drop ball435 roomb left)
(move roomb rooma)
(pick ball436 rooma left)
(move rooma roomb)
(drop ball436 roomb left)
(move roomb rooma)
(pick ball437 rooma left)
(move rooma roomb)
(drop ball437 roomb left)
(move roomb rooma)
(pick ball438 rooma left)
(move rooma roomb)
(drop ball438 roomb left)
(move roomb rooma)
(pick ball439 rooma left)
(move rooma roomb)
(drop ball439 roomb left)
(move roomb rooma)
(pick ball44 rooma left)
(move rooma roomb)
(drop ball44 roomb left)
(move roomb rooma)
(pick ball440 rooma left)
(move rooma roomb)
(drop ball440 roomb left)
(move roomb rooma)
(pick ball441 rooma left)
(move rooma roomb)
(drop ball441 roomb left)
(move roomb rooma)
(pick ball442 rooma left)
(move rooma roomb)
(drop ball442 roomb left)
(move roomb rooma)
(pick ball443 rooma left)
(move rooma roomb)
(drop ball443 roomb left)
(move roomb rooma)
(pick ball444 rooma left)
(move rooma roomb)
(drop ball444 roomb left)
(move roomb rooma)
(pick ball445 rooma left)
(move rooma roomb)
(drop ball445 roomb left)
(move roomb rooma)
(pick ball446 rooma left)
(move rooma roomb)
(drop ball446 roomb left)
(move roomb rooma)
(pick ball447 rooma left)
(move rooma roomb)
(drop ball447 roomb left)
(move roomb rooma)
(pick ball448 rooma left)
(move rooma roomb)
(drop ball448 roomb left)
(move roomb rooma)
(pick ball449 rooma left)
(move rooma roomb)
(drop ball449 roomb left)
(move roomb rooma)
(pick ball45 rooma left)
(move rooma roomb)
(drop ball45 roomb left)
(move roomb rooma)
(pick ball450 rooma left)
(move rooma roomb)
(drop ball450 roomb left)
(move roomb rooma)
(pick ball451 rooma left)
(move rooma roomb)
(drop ball451 roomb left)
(move roomb rooma)
(pick ball452 rooma left)
(move rooma roomb)
(drop ball452 roomb left)
(move roomb rooma)
(pick ball453 rooma left)
(move rooma roomb)
(drop ball453 roomb left)
(move roomb rooma)
(pick ball454 rooma left)
(move rooma roomb)
(drop ball454 roomb left)
(move roomb rooma)
(pick ball455 rooma left)
(move rooma roomb)
(drop ball455 roomb left)
(move roomb rooma)
(pick ball456 rooma left)
(move rooma roomb)
(drop ball456 roomb left)
(move roomb rooma)
(pick ball457 rooma left)
(move rooma roomb)
(drop ball457 roomb left)
(move roomb rooma)
(pick ball458 rooma right)
(move rooma roomb)
(drop ball458 roomb right)
(move roomb rooma)
(pick ball459 rooma right)
(move rooma roomb)
(drop ball459 roomb right)
(move roomb rooma)
(pick ball46 rooma left)
(move rooma roomb)
(drop ball46 roomb left)
(move roomb rooma)
(pick ball460 rooma left)
(move rooma roomb)
(drop ball460 roomb left)
(move roomb rooma)
(pick ball461 rooma left)
(move rooma roomb)
(drop ball461 roomb left)
(move roomb rooma)
(pick ball462 rooma left)
(move rooma roomb)
(drop ball462 roomb left)
(move roomb rooma)
(pick ball463 rooma left)
(move rooma roomb)
(drop ball463 roomb left)
(move roomb rooma)
(pick ball464 rooma left)
(move rooma roomb)
(drop ball464 roomb left)
(move roomb rooma)
(pick ball465 rooma left)
(move rooma roomb)
(drop ball465 roomb left)
(move roomb rooma)
(pick ball466 rooma left)
(move rooma roomb)
(drop ball466 roomb left)
(move roomb rooma)
(pick ball467 rooma left)
(move rooma roomb)
(drop ball467 roomb left)
(move roomb rooma)
(pick ball468 rooma left)
(move rooma roomb)
(drop ball468 roomb left)
(move roomb rooma)
(pick ball469 rooma left)
(move rooma roomb)
(drop ball469 roomb left)
(move roomb rooma)
(pick ball47 rooma left)
(move rooma roomb)
(drop ball47 roomb left)
(move roomb rooma)
(pick ball470 rooma left)
(move rooma roomb)
(drop ball470 roomb left)
(move roomb rooma)
(pick ball471 rooma left)
(move rooma roomb)
(drop ball471 roomb left)
(move roomb rooma)
(pick ball472 rooma left)
(move rooma roomb)
(drop ball472 roomb left)
(move roomb rooma)
(pick ball473 rooma left)
(move rooma roomb)
(drop ball473 roomb left)
(move roomb rooma)
(pick ball474 rooma left)
(move rooma roomb)
(drop ball474 roomb left)
(move roomb rooma)
(pick ball475 rooma left)
(move rooma roomb)
(drop ball475 roomb left)
(move roomb rooma)
(pick ball476 rooma left)
(move rooma roomb)
(drop ball476 roomb left)
(move roomb rooma)
(pick ball477 rooma left)
(move rooma roomb)
(drop ball477 roomb left)
(move roomb rooma)
(pick ball478 rooma left)
(move rooma roomb)
(drop ball478 roomb left)
(move roomb rooma)
(pick ball479 rooma left)
(move rooma roomb)
(drop ball479 roomb left)
(move roomb rooma)
(pick ball48 rooma left)
(move rooma roomb)
(drop ball48 roomb left)
(move roomb rooma)
(pick ball480 rooma left)
(move rooma roomb)
(drop ball480 roomb left)
(move roomb rooma)
(pick ball481 rooma left)
(move rooma roomb)
(drop ball481 roomb left)
(move roomb rooma)
(pick ball482 rooma left)
(move rooma roomb)
(drop ball482 roomb left)
(move roomb rooma)
(pick ball483 rooma left)
(move rooma roomb)
(drop ball483 roomb left)
(move roomb rooma)
(pick ball484 rooma left)
(move rooma roomb)
(drop ball484 roomb left)
(move roomb rooma)
(pick ball485 rooma left)
(move rooma roomb)
(drop ball485 roomb left)
(move roomb rooma)
(pick ball486 rooma left)
(move rooma roomb)
(drop ball486 roomb left)
(move roomb rooma)
(pick ball487 rooma left)
(move rooma roomb)
(drop ball487 roomb left)
(move roomb rooma)
(pick ball488 rooma left)
(move rooma roomb)
(drop ball488 roomb left)
(move roomb rooma)
(pick ball489 rooma left)
(move rooma roomb)
(drop ball489 roomb left)
(move roomb rooma)
(pick ball49 rooma left)
(move rooma roomb)
(drop ball49 roomb left)
(move roomb rooma)
(pick ball490 rooma left)
(move rooma roomb)
(drop ball490 roomb left)
(move roomb rooma)
(pick ball491 rooma left)
(move rooma roomb)
(drop ball491 roomb left)
(move roomb rooma)
(pick ball492 rooma left)
(move rooma roomb)
(drop ball492 roomb left)
(move roomb rooma)
(pick ball493 rooma left)
(move rooma roomb)
(drop ball493 roomb left)
(move roomb rooma)
(pick ball494 rooma left)
(move rooma roomb)
(drop ball494 roomb left)
(move roomb rooma)
(pick ball495 rooma left)
(move rooma roomb)
(drop ball495 roomb left)
(move roomb rooma)
(pick ball496 rooma left)
(move rooma roomb)
(drop ball496 roomb left)
(move roomb rooma)
(pick ball497 rooma left)
(move rooma roomb)
(drop ball497 roomb left)
(move roomb rooma)
(pick ball498 rooma left)
(move rooma roomb)
(drop ball498 roomb left)
(move roomb rooma)
(pick ball499 rooma left)
(move rooma roomb)
(drop ball499 roomb left)
(move roomb rooma)
(pick ball5 rooma left)
(move rooma roomb)
(drop ball5 roomb left)
(move roomb rooma)
(pick ball50 rooma left)
(move rooma roomb)
(drop ball50 roomb left)
(move roomb rooma)
(pick ball500 rooma left)
(move rooma roomb)
(drop ball500 roomb left)
(move roomb rooma)
(pick ball501 rooma left)
(move rooma roomb)
(drop ball501 roomb left)
(move roomb rooma)
(pick ball502 rooma left)
(move rooma roomb)
(drop ball502 roomb left)
(move roomb rooma)
(pick ball503 rooma left)
(move rooma roomb)
(drop ball503 roomb left)
(move roomb rooma)
(pick ball504 rooma left)
(move rooma roomb)
(drop ball504 roomb left)
(move roomb rooma)
(pick ball505 rooma left)
(move rooma roomb)
(drop ball505 roomb left)
(move roomb rooma)
(pick ball506 rooma left)
(move rooma roomb)
(drop ball506 roomb left)
(move roomb rooma)
(pick ball507 rooma left)
(move rooma roomb)
(drop ball507 roomb left)
(move roomb rooma)
(pick ball508 rooma left)
(move rooma roomb)
(drop ball508 roomb left)
(move roomb rooma)
(pick ball509 rooma right)
(move rooma roomb)
(drop ball509 roomb right)
(move roomb rooma)
(pick ball51 rooma left)
(move rooma roomb)
(drop ball51 roomb left)
(move roomb rooma)
(pick ball510 rooma left)
(move rooma roomb)
(drop ball510 roomb left)
(move roomb rooma)
(pick ball511 rooma left)
(move rooma roomb)
(drop ball511 roomb left)
(move roomb rooma)
(pick ball512 rooma left)
(move rooma roomb)
(drop ball512 roomb left)
(move roomb rooma)
(pick ball513 rooma left)
(move rooma roomb)
(drop ball513 roomb left)
(move roomb rooma)
(pick ball514 rooma left)
(move rooma roomb)
(drop ball514 roomb left)
(move roomb rooma)
(pick ball515 rooma left)
(move rooma roomb)
(drop ball515 roomb left)
(move roomb rooma)
(pick ball516 rooma left)
(move rooma roomb)
(drop ball516 roomb left)
(move roomb rooma)
(pick ball517 rooma left)
(move rooma roomb)
(drop ball517 roomb left)
(move roomb rooma)
(pick ball518 rooma left)
(move rooma roomb)
(drop ball518 roomb left)
(move roomb rooma)
(pick ball519 rooma left)
(move rooma roomb)
(drop ball519 roomb left)
(move roomb rooma)
(pick ball52 rooma left)
(move rooma roomb)
(drop ball52 roomb left)
(move roomb rooma)
(pick ball520 rooma left)
(move rooma roomb)
(drop ball520 roomb left)
(move roomb rooma)
(pick ball521 rooma left)
(move rooma roomb)
(drop ball521 roomb left)
(move roomb rooma)
(pick ball522 rooma left)
(move rooma roomb)
(drop ball522 roomb left)
(move roomb rooma)
(pick ball523 rooma left)
(move rooma roomb)
(drop ball523 roomb left)
(move roomb rooma)
(pick ball524 rooma left)
(move rooma roomb)
(drop ball524 roomb left)
(move roomb rooma)
(pick ball525 rooma left)
(move rooma roomb)
(drop ball525 roomb left)
(move roomb rooma)
(pick ball526 rooma left)
(move rooma roomb)
(drop ball526 roomb left)
(move roomb rooma)
(pick ball527 rooma left)
(move rooma roomb)
(drop ball527 roomb left)
(move roomb rooma)
(pick ball528 rooma left)
(move rooma roomb)
(drop ball528 roomb left)
(move roomb rooma)
(pick ball529 rooma left)
(move rooma roomb)
(drop ball529 roomb left)
(move roomb rooma)
(pick ball53 rooma left)
(move rooma roomb)
(drop ball53 roomb left)
(move roomb rooma)
(pick ball530 rooma left)
(move rooma roomb)
(drop ball530 roomb left)
(move roomb rooma)
(pick ball531 rooma left)
(move rooma roomb)
(drop ball531 roomb left)
(move roomb rooma)
(pick ball532 rooma left)
(move rooma roomb)
(drop ball532 roomb left)
(move roomb rooma)
(pick ball533 rooma left)
(move rooma roomb)
(drop ball533 roomb left)
(move roomb rooma)
(pick ball534 rooma left)
(move rooma roomb)
(drop ball534 roomb left)
(move roomb rooma)
(pick ball535 rooma left)
(move rooma roomb)
(drop ball535 roomb left)
(move roomb rooma)
(pick ball536 rooma left)
(move rooma roomb)
(drop ball536 roomb left)
(move roomb rooma)
(pick ball537 rooma left)
(move rooma roomb)
(drop ball537 roomb left)
(move roomb rooma)
(pick ball538 rooma left)
(move rooma roomb)
(drop ball538 roomb left)
(move roomb rooma)
(pick ball539 rooma left)
(move rooma roomb)
(drop ball539 roomb left)
(move roomb rooma)
(pick ball54 rooma left)
(move rooma roomb)
(drop ball54 roomb left)
(move roomb rooma)
(pick ball540 rooma left)
(move rooma roomb)
(drop ball540 roomb left)
(move roomb rooma)
(pick ball541 rooma left)
(move rooma roomb)
(drop ball541 roomb left)
(move roomb rooma)
(pick ball542 rooma left)
(move rooma roomb)
(drop ball542 roomb left)
(move roomb rooma)
(pick ball543 rooma left)
(move rooma roomb)
(drop ball543 roomb left)
(move roomb rooma)
(pick ball544 rooma left)
(move rooma roomb)
(drop ball544 roomb left)
(move roomb rooma)
(pick ball545 rooma left)
(move rooma roomb)
(drop ball545 roomb left)
(move roomb rooma)
(pick ball546 rooma left)
(move rooma roomb)
(drop ball546 roomb left)
(move roomb rooma)
(pick ball547 rooma left)
(move rooma roomb)
(drop ball547 roomb left)
(move roomb rooma)
(pick ball548 rooma left)
(move rooma roomb)
(drop ball548 roomb left)
(move roomb rooma)
(pick ball549 rooma left)
(move rooma roomb)
(drop ball549 roomb left)
(move roomb rooma)
(pick ball55 rooma left)
(move rooma roomb)
(drop ball55 roomb left)
(move roomb rooma)
(pick ball550 rooma left)
(move rooma roomb)
(drop ball550 roomb left)
(move roomb rooma)
(pick ball551 rooma left)
(move rooma roomb)
(drop ball551 roomb left)
(move roomb rooma)
(pick ball552 rooma left)
(move rooma roomb)
(drop ball552 roomb left)
(move roomb rooma)
(pick ball553 rooma left)
(move rooma roomb)
(drop ball553 roomb left)
(move roomb rooma)
(pick ball554 rooma left)
(move rooma roomb)
(drop ball554 roomb left)
(move roomb rooma)
(pick ball555 rooma left)
(move rooma roomb)
(drop ball555 roomb left)
(move roomb rooma)
(pick ball556 rooma left)
(move rooma roomb)
(drop ball556 roomb left)
(move roomb rooma)
(pick ball557 rooma left)
(move rooma roomb)
(drop ball557 roomb left)
(move roomb rooma)
(pick ball558 rooma left)
(move rooma roomb)
(drop ball558 roomb left)
(move roomb rooma)
(pick ball559 rooma left)
(move rooma roomb)
(drop ball559 roomb left)
(move roomb rooma)
(pick ball56 rooma left)
(move rooma roomb)
(drop ball56 roomb left)
(move roomb rooma)
(pick ball560 rooma right)
(move rooma roomb)
(drop ball560 roomb right)
(move roomb rooma)
(pick ball561 rooma left)
(move rooma roomb)
(drop ball561 roomb left)
(move roomb rooma)
(pick ball562 rooma left)
(move rooma roomb)
(drop ball562 roomb left)
(move roomb rooma)
(pick ball563 rooma left)
(move rooma roomb)
(drop ball563 roomb left)
(move roomb rooma)
(pick ball564 rooma left)
(move rooma roomb)
(drop ball564 roomb left)
(move roomb rooma)
(pick ball565 rooma left)
(move rooma roomb)
(drop ball565 roomb left)
(move roomb rooma)
(pick ball566 rooma left)
(move rooma roomb)
(drop ball566 roomb left)
(move roomb rooma)
(pick ball567 rooma left)
(move rooma roomb)
(drop ball567 roomb left)
(move roomb rooma)
(pick ball568 rooma left)
(move rooma roomb)
(drop ball568 roomb left)
(move roomb rooma)
(pick ball569 rooma left)
(move rooma roomb)
(drop ball569 roomb left)
(move roomb rooma)
(pick ball57 rooma left)
(move rooma roomb)
(drop ball57 roomb left)
(move roomb rooma)
(pick ball570 rooma left)
(move rooma roomb)
(drop ball570 roomb left)
(move roomb rooma)
(pick ball571 rooma left)
(move rooma roomb)
(drop ball571 roomb left)
(move roomb rooma)
(pick ball572 rooma left)
(move rooma roomb)
(drop ball572 roomb left)
(move roomb rooma)
(pick ball573 rooma left)
(move rooma roomb)
(drop ball573 roomb left)
(move roomb rooma)
(pick ball574 rooma left)
(move rooma roomb)
(drop ball574 roomb left)
(move roomb rooma)
(pick ball575 rooma left)
(move rooma roomb)
(drop ball575 roomb left)
(move roomb rooma)
(pick ball576 rooma left)
(move rooma roomb)
(drop ball576 roomb left)
(move roomb rooma)
(pick ball577 rooma left)
(move rooma roomb)
(drop ball577 roomb left)
(move roomb rooma)
(pick ball578 rooma left)
(move rooma roomb)
(drop ball578 roomb left)
(move roomb rooma)
(pick ball579 rooma left)
(move rooma roomb)
(drop ball579 roomb left)
(move roomb rooma)
(pick ball58 rooma left)
(move rooma roomb)
(drop ball58 roomb left)
(move roomb rooma)
(pick ball580 rooma left)
(move rooma roomb)
(drop ball580 roomb left)
(move roomb rooma)
(pick ball581 rooma left)
(move rooma roomb)
(drop ball581 roomb left)
(move roomb rooma)
(pick ball582 rooma left)
(move rooma roomb)
(drop ball582 roomb left)
(move roomb rooma)
(pick ball583 rooma left)
(move rooma roomb)
(drop ball583 roomb left)
(move roomb rooma)
(pick ball584 rooma left)
(move rooma roomb)
(drop ball584 roomb left)
(move roomb rooma)
(pick ball585 rooma left)
(move rooma roomb)
(drop ball585 roomb left)
(move roomb rooma)
(pick ball586 rooma left)
(move rooma roomb)
(drop ball586 roomb left)
(move roomb rooma)
(pick ball587 rooma left)
(move rooma roomb)
(drop ball587 roomb left)
(move roomb rooma)
(pick ball588 rooma left)
(move rooma roomb)
(drop ball588 roomb left)
(move roomb rooma)
(pick ball589 rooma left)
(move rooma roomb)
(drop ball589 roomb left)
(move roomb rooma)
(pick ball59 rooma left)
(move rooma roomb)
(drop ball59 roomb left)
(move roomb rooma)
(pick ball590 rooma left)
(move rooma roomb)
(drop ball590 roomb left)
(move roomb rooma)
(pick ball591 rooma left)
(move rooma roomb)
(drop ball591 roomb left)
(move roomb rooma)
(pick ball592 rooma left)
(move rooma roomb)
(drop ball592 roomb left)
(move roomb rooma)
(pick ball593 rooma left)
(move rooma roomb)
(drop ball593 roomb left)
(move roomb rooma)
(pick ball594 rooma left)
(move rooma roomb)
(drop ball594 roomb left)
(move roomb rooma)
(pick ball595 rooma left)
(move rooma roomb)
(drop ball595 roomb left)
(move roomb rooma)
(pick ball596 rooma left)
(move rooma roomb)
(drop ball596 roomb left)
(move roomb rooma)
(pick ball597 rooma left)
(move rooma roomb)
(drop ball597 roomb left)
(move roomb rooma)
(pick ball598 rooma left)
(move rooma roomb)
(drop ball598 roomb left)
(move roomb rooma)
(pick ball599 rooma left)
(move rooma roomb)
(drop ball599 roomb left)
(move roomb rooma)
(pick ball6 rooma left)
(move rooma roomb)
(drop ball6 roomb left)
(move roomb rooma)
(pick ball60 rooma left)
(move rooma roomb)
(drop ball60 roomb left)
(move roomb rooma)
(pick ball600 rooma left)
(move rooma roomb)
(drop ball600 roomb left)
(move roomb rooma)
(pick ball601 rooma left)
(move rooma roomb)
(drop ball601 roomb left)
(move roomb rooma)
(pick ball602 rooma left)
(move rooma roomb)
(drop ball602 roomb left)
(move roomb rooma)
(pick ball603 rooma left)
(move rooma roomb)
(drop ball603 roomb left)
(move roomb rooma)
(pick ball604 rooma left)
(move rooma roomb)
(drop ball604 roomb left)
(move roomb rooma)
(pick ball605 rooma left)
(move rooma roomb)
(drop ball605 roomb left)
(move roomb rooma)
(pick ball606 rooma left)
(move rooma roomb)
(drop ball606 roomb left)
(move roomb rooma)
(pick ball607 rooma left)
(move rooma roomb)
(drop ball607 roomb left)
(move roomb rooma)
(pick ball608 rooma left)
(move rooma roomb)
(drop ball608 roomb left)
(move roomb rooma)
(pick ball609 rooma left)
(move rooma roomb)
(drop ball609 roomb left)
(move roomb rooma)
(pick ball61 rooma left)
(move rooma roomb)
(drop ball61 roomb left)
(move roomb rooma)
(pick ball610 rooma right)
(move rooma roomb)
(drop ball610 roomb right)
(move roomb rooma)
(pick ball611 rooma left)
(move rooma roomb)
(drop ball611 roomb left)
(move roomb rooma)
(pick ball612 rooma left)
(move rooma roomb)
(drop ball612 roomb left)
(move roomb rooma)
(pick ball613 rooma left)
(move rooma roomb)
(drop ball613 roomb left)
(move roomb rooma)
(pick ball614 rooma left)
(move rooma roomb)
(drop ball614 roomb left)
(move roomb rooma)
(pick ball615 rooma left)
(move rooma roomb)
(drop ball615 roomb left)
(move roomb rooma)
(pick ball616 rooma left)
(move rooma roomb)
(drop ball616 roomb left)
(move roomb rooma)
(pick ball617 rooma left)
(move rooma roomb)
(drop ball617 roomb left)
(move roomb rooma)
(pick ball618 rooma left)
(move rooma roomb)
(drop ball618 roomb left)
(move roomb rooma)
(pick ball619 rooma left)
(move rooma roomb)
(drop ball619 roomb left)
(move roomb rooma)
(pick ball62 rooma left)
(move rooma roomb)
(drop ball62 roomb left)
(move roomb rooma)
(pick ball620 rooma left)
(move rooma roomb)
(drop ball620 roomb left)
(move roomb rooma)
(pick ball621 rooma left)
(move rooma roomb)
(drop ball621 roomb left)
(move roomb rooma)
(pick ball622 rooma left)
(move rooma roomb)
(drop ball622 roomb left)
(move roomb rooma)
(pick ball623 rooma left)
(move rooma roomb)
(drop ball623 roomb left)
(move roomb rooma)
(pick ball624 rooma left)
(move rooma roomb)
(drop ball624 roomb left)
(move roomb rooma)
(pick ball625 rooma left)
(move rooma roomb)
(drop ball625 roomb left)
(move roomb rooma)
(pick ball626 rooma left)
(move rooma roomb)
(drop ball626 roomb left)
(move roomb rooma)
(pick ball627 rooma left)
(move rooma roomb)
(drop ball627 roomb left)
(move roomb rooma)
(pick ball628 rooma left)
(move rooma roomb)
(drop ball628 roomb left)
(move roomb rooma)
(pick ball629 rooma left)
(move rooma roomb)
(drop ball629 roomb left)
(move roomb rooma)
(pick ball63 rooma left)
(move rooma roomb)
(drop ball63 roomb left)
(move roomb rooma)
(pick ball630 rooma left)
(move rooma roomb)
(drop ball630 roomb left)
(move roomb rooma)
(pick ball631 rooma left)
(move rooma roomb)
(drop ball631 roomb left)
(move roomb rooma)
(pick ball632 rooma left)
(move rooma roomb)
(drop ball632 roomb left)
(move roomb rooma)
(pick ball633 rooma left)
(move rooma roomb)
(drop ball633 roomb left)
(move roomb rooma)
(pick ball634 rooma left)
(move rooma roomb)
(drop ball634 roomb left)
(move roomb rooma)
(pick ball635 rooma left)
(move rooma roomb)
(drop ball635 roomb left)
(move roomb rooma)
(pick ball636 rooma left)
(move rooma roomb)
(drop ball636 roomb left)
(move roomb rooma)
(pick ball637 rooma left)
(move rooma roomb)
(drop ball637 roomb left)
(move roomb rooma)
(pick ball638 rooma left)
(move rooma roomb)
(drop ball638 roomb left)
(move roomb rooma)
(pick ball639 rooma left)
(move rooma roomb)
(drop ball639 roomb left)
(move roomb rooma)
(pick ball64 rooma left)
(move rooma roomb)
(drop ball64 roomb left)
(move roomb rooma)
(pick ball640 rooma left)
(move rooma roomb)
(drop ball640 roomb left)
(move roomb rooma)
(pick ball641 rooma left)
(move rooma roomb)
(drop ball641 roomb left)
(move roomb rooma)
(pick ball642 rooma left)
(move rooma roomb)
(drop ball642 roomb left)
(move roomb rooma)
(pick ball643 rooma left)
(move rooma roomb)
(drop ball643 roomb left)
(move roomb rooma)
(pick ball644 rooma left)
(move rooma roomb)
(drop ball644 roomb left)
(move roomb rooma)
(pick ball645 rooma left)
(move rooma roomb)
(drop ball645 roomb left)
(move roomb rooma)
(pick ball646 rooma left)
(move rooma roomb)
(drop ball646 roomb left)
(move roomb rooma)
(pick ball647 rooma left)
(move rooma roomb)
(drop ball647 roomb left)
(move roomb rooma)
(pick ball648 rooma left)
(move rooma roomb)
(drop ball648 roomb left)
(move roomb rooma)
(pick ball649 rooma left)
(move rooma roomb)
(drop ball649 roomb left)
(move roomb rooma)
(pick ball65 rooma left)
(move rooma roomb)
(drop ball65 roomb left)
(move roomb rooma)
(pick ball650 rooma left)
(move rooma roomb)
(drop ball650 roomb left)
(move roomb rooma)
(pick ball651 rooma left)
(move rooma roomb)
(drop ball651 roomb left)
(move roomb rooma)
(pick ball652 rooma left)
(move rooma roomb)
(drop ball652 roomb left)
(move roomb rooma)
(pick ball653 rooma left)
(move rooma roomb)
(drop ball653 roomb left)
(move roomb rooma)
(pick ball654 rooma left)
(move rooma roomb)
(drop ball654 roomb left)
(move roomb rooma)
(pick ball655 rooma left)
(move rooma roomb)
(drop ball655 roomb left)
(move roomb rooma)
(pick ball656 rooma left)
(move rooma roomb)
(drop ball656 roomb left)
(move roomb rooma)
(pick ball657 rooma left)
(move rooma roomb)
(drop ball657 roomb left)
(move roomb rooma)
(pick ball658 rooma left)
(move rooma roomb)
(drop ball658 roomb left)
(move roomb rooma)
(pick ball659 rooma left)
(move rooma roomb)
(drop ball659 roomb left)
(move roomb rooma)
(pick ball66 rooma left)
(move rooma roomb)
(drop ball66 roomb left)
(move roomb rooma)
(pick ball660 rooma left)
(move rooma roomb)
(drop ball660 roomb left)
(move roomb rooma)
(pick ball661 rooma left)
(move rooma roomb)
(drop ball661 roomb left)
(move roomb rooma)
(pick ball662 rooma right)
(move rooma roomb)
(drop ball662 roomb right)
(move roomb rooma)
(pick ball663 rooma left)
(move rooma roomb)
(drop ball663 roomb left)
(move roomb rooma)
(pick ball664 rooma left)
(move rooma roomb)
(drop ball664 roomb left)
(move roomb rooma)
(pick ball665 rooma left)
(move rooma roomb)
(drop ball665 roomb left)
(move roomb rooma)
(pick ball666 rooma left)
(move rooma roomb)
(drop ball666 roomb left)
(move roomb rooma)
(pick ball667 rooma left)
(move rooma roomb)
(drop ball667 roomb left)
(move roomb rooma)
(pick ball668 rooma left)
(move rooma roomb)
(drop ball668 roomb left)
(move roomb rooma)
(pick ball669 rooma left)
(move rooma roomb)
(drop ball669 roomb left)
(move roomb rooma)
(pick ball67 rooma left)
(move rooma roomb)
(drop ball67 roomb left)
(move roomb rooma)
(pick ball670 rooma left)
(move rooma roomb)
(drop ball670 roomb left)
(move roomb rooma)
(pick ball671 rooma left)
(move rooma roomb)
(drop ball671 roomb left)
(move roomb rooma)
(pick ball672 rooma left)
(move rooma roomb)
(drop ball672 roomb left)
(move roomb rooma)
(pick ball673 rooma left)
(move rooma roomb)
(drop ball673 roomb left)
(move roomb rooma)
(pick ball674 rooma left)
(move rooma roomb)
(drop ball674 roomb left)
(move roomb rooma)
(pick ball675 rooma left)
(move rooma roomb)
(drop ball675 roomb left)
(move roomb rooma)
(pick ball676 rooma left)
(move rooma roomb)
(drop ball676 roomb left)
(move roomb rooma)
(pick ball677 rooma left)
(move rooma roomb)
(drop ball677 roomb left)
(move roomb rooma)
(pick ball678 rooma left)
(move rooma roomb)
(drop ball678 roomb left)
(move roomb rooma)
(pick ball679 rooma left)
(move rooma roomb)
(drop ball679 roomb left)
(move roomb rooma)
(pick ball68 rooma left)
(move rooma roomb)
(drop ball68 roomb left)
(move roomb rooma)
(pick ball680 rooma left)
(move rooma roomb)
(drop ball680 roomb left)
(move roomb rooma)
(pick ball681 rooma left)
(move rooma roomb)
(drop ball681 roomb left)
(move roomb rooma)
(pick ball682 rooma left)
(move rooma roomb)
(drop ball682 roomb left)
(move roomb rooma)
(pick ball683 rooma left)
(move rooma roomb)
(drop ball683 roomb left)
(move roomb rooma)
(pick ball684 rooma left)
(move rooma roomb)
(drop ball684 roomb left)
(move roomb rooma)
(pick ball685 rooma left)
(move rooma roomb)
(drop ball685 roomb left)
(move roomb rooma)
(pick ball686 rooma left)
(move rooma roomb)
(drop ball686 roomb left)
(move roomb rooma)
(pick ball687 rooma left)
(move rooma roomb)
(drop ball687 roomb left)
(move roomb rooma)
(pick ball688 rooma left)
(move rooma roomb)
(drop ball688 roomb left)
(move roomb rooma)
(pick ball689 rooma left)
(move rooma roomb)
(drop ball689 roomb left)
(move roomb rooma)
(pick ball69 rooma left)
(move rooma roomb)
(drop ball69 roomb left)
(move roomb rooma)
(pick ball690 rooma left)
(move rooma roomb)
(drop ball690 roomb left)
(move roomb rooma)
(pick ball691 rooma left)
(move rooma roomb)
(drop ball691 roomb left)
(move roomb rooma)
(pick ball692 rooma left)
(move rooma roomb)
(drop ball692 roomb left)
(move roomb rooma)
(pick ball693 rooma left)
(move rooma roomb)
(drop ball693 roomb left)
(move roomb rooma)
(pick ball694 rooma left)
(move rooma roomb)
(drop ball694 roomb left)
(move roomb rooma)
(pick ball695 rooma left)
(move rooma roomb)
(drop ball695 roomb left)
(move roomb rooma)
(pick ball696 rooma left)
(move rooma roomb)
(drop ball696 roomb left)
(move roomb rooma)
(pick ball697 rooma left)
(move rooma roomb)
(drop ball697 roomb left)
(move roomb rooma)
(pick ball698 rooma left)
(move rooma roomb)
(drop ball698 roomb left)
(move roomb rooma)
(pick ball699 rooma left)
(move rooma roomb)
(drop ball699 roomb left)
(move roomb rooma)
(pick ball7 rooma left)
(move rooma roomb)
(drop ball7 roomb left)
(move roomb rooma)
(pick ball70 rooma left)
(move rooma roomb)
(drop ball70 roomb left)
(move roomb rooma)
(pick ball700 rooma left)
(move rooma roomb)
(drop ball700 roomb left)
(move roomb rooma)
(pick ball701 rooma left)
(move rooma roomb)
(drop ball701 roomb left)
(move roomb rooma)
(pick ball702 rooma left)
(move rooma roomb)
(drop ball702 roomb left)
(move roomb rooma)
(pick ball703 rooma left)
(move rooma roomb)
(drop ball703 roomb left)
(move roomb rooma)
(pick ball704 rooma left)
(move rooma roomb)
(drop ball704 roomb left)
(move roomb rooma)
(pick ball705 rooma left)
(move rooma roomb)
(drop ball705 roomb left)
(move roomb rooma)
(pick ball706 rooma left)
(move rooma roomb)
(drop ball706 roomb left)
(move roomb rooma)
(pick ball707 rooma left)
(move rooma roomb)
(drop ball707 roomb left)
(move roomb rooma)
(pick ball708 rooma left)
(move rooma roomb)
(drop ball708 roomb left)
(move roomb rooma)
(pick ball709 rooma left)
(move rooma roomb)
(drop ball709 roomb left)
(move roomb rooma)
(pick ball71 rooma left)
(move rooma roomb)
(drop ball71 roomb left)
(move roomb rooma)
(pick ball710 rooma left)
(move rooma roomb)
(drop ball710 roomb left)
(move roomb rooma)
(pick ball711 rooma left)
(move rooma roomb)
(drop ball711 roomb left)
(move roomb rooma)
(pick ball712 rooma left)
(move rooma roomb)
(drop ball712 roomb left)
(move roomb rooma)
(pick ball713 rooma right)
(move rooma roomb)
(drop ball713 roomb right)
(move roomb rooma)
(pick ball714 rooma left)
(move rooma roomb)
(drop ball714 roomb left)
(move roomb rooma)
(pick ball715 rooma left)
(move rooma roomb)
(drop ball715 roomb left)
(move roomb rooma)
(pick ball716 rooma left)
(move rooma roomb)
(drop ball716 roomb left)
(move roomb rooma)
(pick ball717 rooma left)
(move rooma roomb)
(drop ball717 roomb left)
(move roomb rooma)
(pick ball718 rooma left)
(move rooma roomb)
(drop ball718 roomb left)
(move roomb rooma)
(pick ball719 rooma left)
(move rooma roomb)
(drop ball719 roomb left)
(move roomb rooma)
(pick ball72 rooma left)
(move rooma roomb)
(drop ball72 roomb left)
(move roomb rooma)
(pick ball720 rooma left)
(move rooma roomb)
(drop ball720 roomb left)
(move roomb rooma)
(pick ball721 rooma left)
(move rooma roomb)
(drop ball721 roomb left)
(move roomb rooma)
(pick ball722 rooma left)
(move rooma roomb)
(drop ball722 roomb left)
(move roomb rooma)
(pick ball723 rooma left)
(move rooma roomb)
(drop ball723 roomb left)
(move roomb rooma)
(pick ball724 rooma left)
(move rooma roomb)
(drop ball724 roomb left)
(move roomb rooma)
(pick ball725 rooma left)
(move rooma roomb)
(drop ball725 roomb left)
(move roomb rooma)
(pick ball726 rooma left)
(move rooma roomb)
(drop ball726 roomb left)
(move roomb rooma)
(pick ball727 rooma left)
(move rooma roomb)
(drop ball727 roomb left)
(move roomb rooma)
(pick ball728 rooma left)
(move rooma roomb)
(drop ball728 roomb left)
(move roomb rooma)
(pick ball729 rooma left)
(move rooma roomb)
(drop ball729 roomb left)
(move roomb rooma)
(pick ball73 rooma left)
(move rooma roomb)
(drop ball73 roomb left)
(move roomb rooma)
(pick ball730 rooma left)
(move rooma roomb)
(drop ball730 roomb left)
(move roomb rooma)
(pick ball731 rooma left)
(move rooma roomb)
(drop ball731 roomb left)
(move roomb rooma)
(pick ball732 rooma left)
(move rooma roomb)
(drop ball732 roomb left)
(move roomb rooma)
(pick ball733 rooma left)
(move rooma roomb)
(drop ball733 roomb left)
(move roomb rooma)
(pick ball734 rooma left)
(move rooma roomb)
(drop ball734 roomb left)
(move roomb rooma)
(pick ball735 rooma left)
(move rooma roomb)
(drop ball735 roomb left)
(move roomb rooma)
(pick ball736 rooma left)
(move rooma roomb)
(drop ball736 roomb left)
(move roomb rooma)
(pick ball737 rooma left)
(move rooma roomb)
(drop ball737 roomb left)
(move roomb rooma)
(pick ball738 rooma left)
(move rooma roomb)
(drop ball738 roomb left)
(move roomb rooma)
(pick ball739 rooma left)
(move rooma roomb)
(drop ball739 roomb left)
(move roomb rooma)
(pick ball74 rooma left)
(move rooma roomb)
(drop ball74 roomb left)
(move roomb rooma)
(pick ball740 rooma left)
(move rooma roomb)
(drop ball740 roomb left)
(move roomb rooma)
(pick ball741 rooma left)
(move rooma roomb)
(drop ball741 roomb left)
(move roomb rooma)
(pick ball742 rooma left)
(move rooma roomb)
(drop ball742 roomb left)
(move roomb rooma)
(pick ball743 rooma left)
(move rooma roomb)
(drop ball743 roomb left)
(move roomb rooma)
(pick ball744 rooma left)
(move rooma roomb)
(drop ball744 roomb left)
(move roomb rooma)
(pick ball745 rooma left)
(move rooma roomb)
(drop ball745 roomb left)
(move roomb rooma)
(pick ball746 rooma left)
(move rooma roomb)
(drop ball746 roomb left)
(move roomb rooma)
(pick ball747 rooma left)
(move rooma roomb)
(drop ball747 roomb left)
(move roomb rooma)
(pick ball748 rooma left)
(move rooma roomb)
(drop ball748 roomb left)
(move roomb rooma)
(pick ball749 rooma left)
(move rooma roomb)
(drop ball749 roomb left)
(move roomb rooma)
(pick ball75 rooma left)
(move rooma roomb)
(drop ball75 roomb left)
(move roomb rooma)
(pick ball750 rooma left)
(move rooma roomb)
(drop ball750 roomb left)
(move roomb rooma)
(pick ball751 rooma left)
(move rooma roomb)
(drop ball751 roomb left)
(move roomb rooma)
(pick ball752 rooma left)
(move rooma roomb)
(drop ball752 roomb left)
(move roomb rooma)
(pick ball753 rooma left)
(move rooma roomb)
(drop ball753 roomb left)
(move roomb rooma)
(pick ball754 rooma left)
(move rooma roomb)
(drop ball754 roomb left)
(move roomb rooma)
(pick ball755 rooma left)
(move rooma roomb)
(drop ball755 roomb left)
(move roomb rooma)
(pick ball756 rooma left)
(move rooma roomb)
(drop ball756 roomb left)
(move roomb rooma)
(pick ball757 rooma left)
(move rooma roomb)
(drop ball757 roomb left)
(move roomb rooma)
(pick ball758 rooma left)
(move rooma roomb)
(drop ball758 roomb left)
(move roomb rooma)
(pick ball759 rooma left)
(move rooma roomb)
(drop ball759 roomb left)
(move roomb rooma)
(pick ball76 rooma left)
(move rooma roomb)
(drop ball76 roomb left)
(move roomb rooma)
(pick ball760 rooma left)
(move rooma roomb)
(drop ball760 roomb left)
(move roomb rooma)
(pick ball761 rooma left)
(move rooma roomb)
(drop ball761 roomb left)
(move roomb rooma)
(pick ball762 rooma left)
(move rooma roomb)
(drop ball762 roomb left)
(move roomb rooma)
(pick ball763 rooma left)
(move rooma roomb)
(drop ball763 roomb left)
(move roomb rooma)
(pick ball764 rooma right)
(move rooma roomb)
(drop ball764 roomb right)
(move roomb rooma)
(pick ball765 rooma left)
(move rooma roomb)
(drop ball765 roomb left)
(move roomb rooma)
(pick ball766 rooma left)
(move rooma roomb)
(drop ball766 roomb left)
(move roomb rooma)
(pick ball767 rooma left)
(move rooma roomb)
(drop ball767 roomb left)
(move roomb rooma)
(pick ball768 rooma left)
(move rooma roomb)
(drop ball768 roomb left)
(move roomb rooma)
(pick ball769 rooma left)
(move rooma roomb)
(drop ball769 roomb left)
(move roomb rooma)
(pick ball77 rooma left)
(move rooma roomb)
(drop ball77 roomb left)
(move roomb rooma)
(pick ball770 rooma left)
(move rooma roomb)
(drop ball770 roomb left)
(move roomb rooma)
(pick ball771 rooma left)
(move rooma roomb)
(drop ball771 roomb left)
(move roomb rooma)
(pick ball772 rooma left)
(move rooma roomb)
(drop ball772 roomb left)
(move roomb rooma)
(pick ball773 rooma left)
(move rooma roomb)
(drop ball773 roomb left)
(move roomb rooma)
(pick ball774 rooma left)
(move rooma roomb)
(drop ball774 roomb left)
(move roomb rooma)
(pick ball775 rooma left)
(move rooma roomb)
(drop ball775 roomb left)
(move roomb rooma)
(pick ball776 rooma left)
(move rooma roomb)
(drop ball776 roomb left)
(move roomb rooma)
(pick ball777 rooma left)
(move rooma roomb)
(drop ball777 roomb left)
(move roomb rooma)
(pick ball778 rooma left)
(move rooma roomb)
(drop ball778 roomb left)
(move roomb rooma)
(pick ball779 rooma left)
(move rooma roomb)
(drop ball779 roomb left)
(move roomb rooma)
(pick ball78 rooma left)
(move rooma roomb)
(drop ball78 roomb left)
(move roomb rooma)
(pick ball780 rooma left)
(move rooma roomb)
(drop ball780 roomb left)
(move roomb rooma)
(pick ball781 rooma left)
(move rooma roomb)
(drop ball781 roomb left)
(move roomb rooma)
(pick ball782 rooma left)
(move rooma roomb)
(drop ball782 roomb left)
(move roomb rooma)
(pick ball783 rooma left)
(move rooma roomb)
(drop ball783 roomb left)
(move roomb rooma)
(pick ball784 rooma left)
(move rooma roomb)
(drop ball784 roomb left)
(move roomb rooma)
(pick ball785 rooma left)
(move rooma roomb)
(drop ball785 roomb left)
(move roomb rooma)
(pick ball786 rooma left)
(move rooma roomb)
(drop ball786 roomb left)
(move roomb rooma)
(pick ball787 rooma left)
(move rooma roomb)
(drop ball787 roomb left)
(move roomb rooma)
(pick ball788 rooma left)
(move rooma roomb)
(drop ball788 roomb left)
(move roomb rooma)
(pick ball789 rooma left)
(move rooma roomb)
(drop ball789 roomb left)
(move roomb rooma)
(pick ball79 rooma left)
(move rooma roomb)
(drop ball79 roomb left)
(move roomb rooma)
(pick ball790 rooma left)
(move rooma roomb)
(drop ball790 roomb left)
(move roomb rooma)
(pick ball791 rooma left)
(move rooma roomb)
(drop ball791 roomb left)
(move roomb rooma)
(pick ball792 rooma left)
(move rooma roomb)
(drop ball792 roomb left)
(move roomb rooma)
(pick ball793 rooma left)
(move rooma roomb)
(drop ball793 roomb left)
(move roomb rooma)
(pick ball794 rooma left)
(move rooma roomb)
(drop ball794 roomb left)
(move roomb rooma)
(pick ball795 rooma left)
(move rooma roomb)
(drop ball795 roomb left)
(move roomb rooma)
(pick ball796 rooma left)
(move rooma roomb)
(drop ball796 roomb left)
(move roomb rooma)
(pick ball797 rooma left)
(move rooma roomb)
(drop ball797 roomb left)
(move roomb rooma)
(pick ball798 rooma left)
(move rooma roomb)
(drop ball798 roomb left)
(move roomb rooma)
(pick ball799 rooma left)
(move rooma roomb)
(drop ball799 roomb left)
(move roomb rooma)
(pick ball8 rooma left)
(move rooma roomb)
(drop ball8 roomb left)
(move roomb rooma)
(pick ball80 rooma left)
(move rooma roomb)
(drop ball80 roomb left)
(move roomb rooma)
(pick ball800 rooma left)
(move rooma roomb)
(drop ball800 roomb left)
(move roomb rooma)
(pick ball801 rooma left)
(move rooma roomb)
(drop ball801 roomb left)
(move roomb rooma)
(pick ball802 rooma left)
(move rooma roomb)
(drop ball802 roomb left)
(move roomb rooma)
(pick ball803 rooma left)
(move rooma roomb)
(drop ball803 roomb left)
(move roomb rooma)
(pick ball804 rooma left)
(move rooma roomb)
(drop ball804 roomb left)
(move roomb rooma)
(pick ball805 rooma left)
(move rooma roomb)
(drop ball805 roomb left)
(move roomb rooma)
(pick ball806 rooma left)
(move rooma roomb)
(drop ball806 roomb left)
(move roomb rooma)
(pick ball807 rooma left)
(move rooma roomb)
(drop ball807 roomb left)
(move roomb rooma)
(pick ball808 rooma left)
(move rooma roomb)
(drop ball808 roomb left)
(move roomb rooma)
(pick ball809 rooma left)
(move rooma roomb)
(drop ball809 roomb left)
(move roomb rooma)
(pick ball81 rooma left)
(move rooma roomb)
(drop ball81 roomb left)
(move roomb rooma)
(pick ball810 rooma left)
(move rooma roomb)
(drop ball810 roomb left)
(move roomb rooma)
(pick ball811 rooma left)
(move rooma roomb)
(drop ball811 roomb left)
(move roomb rooma)
(pick ball812 rooma left)
(move rooma roomb)
(drop ball812 roomb left)
(move roomb rooma)
(pick ball813 rooma left)
(move rooma roomb)
(drop ball813 roomb left)
(move roomb rooma)
(pick ball814 rooma left)
(move rooma roomb)
(drop ball814 roomb left)
(move roomb rooma)
(pick ball815 rooma right)
(move rooma roomb)
(drop ball815 roomb right)
(move roomb rooma)
(pick ball816 rooma left)
(move rooma roomb)
(drop ball816 roomb left)
(move roomb rooma)
(pick ball817 rooma left)
(move rooma roomb)
(drop ball817 roomb left)
(move roomb rooma)
(pick ball818 rooma left)
(move rooma roomb)
(drop ball818 roomb left)
(move roomb rooma)
(pick ball819 rooma left)
(move rooma roomb)
(drop ball819 roomb left)
(move roomb rooma)
(pick ball82 rooma left)
(move rooma roomb)
(drop ball82 roomb left)
(move roomb rooma)
(pick ball820 rooma left)
(move rooma roomb)
(drop ball820 roomb left)
(move roomb rooma)
(pick ball821 rooma left)
(move rooma roomb)
(drop ball821 roomb left)
(move roomb rooma)
(pick ball822 rooma left)
(move rooma roomb)
(drop ball822 roomb left)
(move roomb rooma)
(pick ball823 rooma left)
(move rooma roomb)
(drop ball823 roomb left)
(move roomb rooma)
(pick ball824 rooma left)
(move rooma roomb)
(drop ball824 roomb left)
(move roomb rooma)
(pick ball825 rooma left)
(move rooma roomb)
(drop ball825 roomb left)
(move roomb rooma)
(pick ball826 rooma left)
(move rooma roomb)
(drop ball826 roomb left)
(move roomb rooma)
(pick ball827 rooma left)
(move rooma roomb)
(drop ball827 roomb left)
(move roomb rooma)
(pick ball828 rooma left)
(move rooma roomb)
(drop ball828 roomb left)
(move roomb rooma)
(pick ball829 rooma left)
(move rooma roomb)
(drop ball829 roomb left)
(move roomb rooma)
(pick ball83 rooma left)
(move rooma roomb)
(drop ball83 roomb left)
(move roomb rooma)
(pick ball830 rooma left)
(move rooma roomb)
(drop ball830 roomb left)
(move roomb rooma)
(pick ball831 rooma left)
(move rooma roomb)
(drop ball831 roomb left)
(move roomb rooma)
(pick ball832 rooma left)
(move rooma roomb)
(drop ball832 roomb left)
(move roomb rooma)
(pick ball833 rooma left)
(move rooma roomb)
(drop ball833 roomb left)
(move roomb rooma)
(pick ball834 rooma left)
(move rooma roomb)
(drop ball834 roomb left)
(move roomb rooma)
(pick ball835 rooma left)
(move rooma roomb)
(drop ball835 roomb left)
(move roomb rooma)
(pick ball836 rooma left)
(move rooma roomb)
(drop ball836 roomb left)
(move roomb rooma)
(pick ball837 rooma left)
(move rooma roomb)
(drop ball837 roomb left)
(move roomb rooma)
(pick ball838 rooma left)
(move rooma roomb)
(drop ball838 roomb left)
(move roomb rooma)
(pick ball839 rooma left)
(move rooma roomb)
(drop ball839 roomb left)
(move roomb rooma)
(pick ball84 rooma left)
(move rooma roomb)
(drop ball84 roomb left)
(move roomb rooma)
(pick ball840 rooma left)
(move rooma roomb)
(drop ball840 roomb left)
(move roomb rooma)
(pick ball841 rooma left)
(move rooma roomb)
(drop ball841 roomb left)
(move roomb rooma)
(pick ball842 rooma left)
(move rooma roomb)
(drop ball842 roomb left)
(move roomb rooma)
(pick ball843 rooma left)
(move rooma roomb)
(drop ball843 roomb left)
(move roomb rooma)
(pick ball844 rooma left)
(move rooma roomb)
(drop ball844 roomb left)
(move roomb rooma)
(pick ball845 rooma left)
(move rooma roomb)
(drop ball845 roomb left)
(move roomb rooma)
(pick ball846 rooma left)
(move rooma roomb)
(drop ball846 roomb left)
(move roomb rooma)
(pick ball847 rooma left)
(move rooma roomb)
(drop ball847 roomb left)
(move roomb rooma)
(pick ball848 rooma left)
(move rooma roomb)
(drop ball848 roomb left)
(move roomb rooma)
(pick ball849 rooma left)
(move rooma roomb)
(drop ball849 roomb left)
(move roomb rooma)
(pick ball85 rooma left)
(move rooma roomb)
(drop ball85 roomb left)
(move roomb rooma)
(pick ball850 rooma left)
(move rooma roomb)
(drop ball850 roomb left)
(move roomb rooma)
(pick ball851 rooma left)
(move rooma roomb)
(drop ball851 roomb left)
(move roomb rooma)
(pick ball852 rooma left)
(move rooma roomb)
(drop ball852 roomb left)
(move roomb rooma)
(pick ball853 rooma left)
(move rooma roomb)
(drop ball853 roomb left)
(move roomb rooma)
(pick ball854 rooma left)
(move rooma roomb)
(drop ball854 roomb left)
(move roomb rooma)
(pick ball855 rooma left)
(move rooma roomb)
(drop ball855 roomb left)
(move roomb rooma)
(pick ball856 rooma left)
(move rooma roomb)
(drop ball856 roomb left)
(move roomb rooma)
(pick ball857 rooma left)
(move rooma roomb)
(drop ball857 roomb left)
(move roomb rooma)
(pick ball858 rooma left)
(move rooma roomb)
(drop ball858 roomb left)
(move roomb rooma)
(pick ball859 rooma left)
(move rooma roomb)
(drop ball859 roomb left)
(move roomb rooma)
(pick ball86 rooma left)
(move rooma roomb)
(drop ball86 roomb left)
(move roomb rooma)
(pick ball860 rooma left)
(move rooma roomb)
(drop ball860 roomb left)
(move roomb rooma)
(pick ball861 rooma left)
(move rooma roomb)
(drop ball861 roomb left)
(move roomb rooma)
(pick ball862 rooma left)
(move rooma roomb)
(drop ball862 roomb left)
(move roomb rooma)
(pick ball863 rooma left)
(move rooma roomb)
(drop ball863 roomb left)
(move roomb rooma)
(pick ball864 rooma left)
(move rooma roomb)
(drop ball864 roomb left)
(move roomb rooma)
(pick ball865 rooma left)
(move rooma roomb)
(drop ball865 roomb left)
(move roomb rooma)
(pick ball866 rooma left)
(move rooma roomb)
(drop ball866 roomb left)
(move roomb rooma)
(pick ball867 rooma right)
(move rooma roomb)
(drop ball867 roomb right)
(move roomb rooma)
(pick ball868 rooma left)
(move rooma roomb)
(drop ball868 roomb left)
(move roomb rooma)
(pick ball869 rooma left)
(move rooma roomb)
(drop ball869 roomb left)
(move roomb rooma)
(pick ball87 rooma left)
(move rooma roomb)
(drop ball87 roomb left)
(move roomb rooma)
(pick ball870 rooma left)
(move rooma roomb)
(drop ball870 roomb left)
(move roomb rooma)
(pick ball871 rooma left)
(move rooma roomb)
(drop ball871 roomb left)
(move roomb rooma)
(pick ball872 rooma left)
(move rooma roomb)
(drop ball872 roomb left)
(move roomb rooma)
(pick ball873 rooma left)
(move rooma roomb)
(drop ball873 roomb left)
(move roomb rooma)
(pick ball874 rooma left)
(move rooma roomb)
(drop ball874 roomb left)
(move roomb rooma)
(pick ball875 rooma left)
(move rooma roomb)
(drop ball875 roomb left)
(move roomb rooma)
(pick ball876 rooma left)
(move rooma roomb)
(drop ball876 roomb left)
(move roomb rooma)
(pick ball877 rooma left)
(move rooma roomb)
(drop ball877 roomb left)
(move roomb rooma)
(pick ball878 rooma left)
(move rooma roomb)
(drop ball878 roomb left)
(move roomb rooma)
(pick ball879 rooma left)
(move rooma roomb)
(drop ball879 roomb left)
(move roomb rooma)
(pick ball88 rooma left)
(move rooma roomb)
(drop ball88 roomb left)
(move roomb rooma)
(pick ball880 rooma left)
(move rooma roomb)
(drop ball880 roomb left)
(move roomb rooma)
(pick ball881 rooma left)
(move rooma roomb)
(drop ball881 roomb left)
(move roomb rooma)
(pick ball882 rooma left)
(move rooma roomb)
(drop ball882 roomb left)
(move roomb rooma)
(pick ball883 rooma left)
(move rooma roomb)
(drop ball883 roomb left)
(move roomb rooma)
(pick ball884 rooma left)
(move rooma roomb)
(drop ball884 roomb left)
(move roomb rooma)
(pick ball885 rooma left)
(move rooma roomb)
(drop ball885 roomb left)
(move roomb rooma)
(pick ball886 rooma left)
(move rooma roomb)
(drop ball886 roomb left)
(move roomb rooma)
(pick ball887 rooma left)
(move rooma roomb)
(drop ball887 roomb left)
(move roomb rooma)
(pick ball888 rooma left)
(move rooma roomb)
(drop ball888 roomb left)
(move roomb rooma)
(pick ball889 rooma left)
(move rooma roomb)
(drop ball889 roomb left)
(move roomb rooma)
(pick ball89 rooma left)
(move rooma roomb)
(drop ball89 roomb left)
(move roomb rooma)
(pick ball890 rooma left)
(move rooma roomb)
(drop ball890 roomb left)
(move roomb rooma)
(pick ball891 rooma left)
(move rooma roomb)
(drop ball891 roomb left)
(move roomb rooma)
(pick ball892 rooma left)
(move rooma roomb)
(drop ball892 roomb left)
(move roomb rooma)
(pick ball893 rooma left)
(move rooma roomb)
(drop ball893 roomb left)
(move roomb rooma)
(pick ball894 rooma left)
(move rooma roomb)
(drop ball894 roomb left)
(move roomb rooma)
(pick ball895 rooma left)
(move rooma roomb)
(drop ball895 roomb left)
(move roomb rooma)
(pick ball896 rooma left)
(move rooma roomb)
(drop ball896 roomb left)
(move roomb rooma)
(pick ball897 rooma left)
(move rooma roomb)
(drop ball897 roomb left)
(move roomb rooma)
(pick ball898 rooma left)
(move rooma roomb)
(drop ball898 roomb left)
(move roomb rooma)
(pick ball899 rooma left)
(move rooma roomb)
(drop ball899 roomb left)
(move roomb rooma)
(pick ball9 rooma left)
(move rooma roomb)
(drop ball9 roomb left)
(move roomb rooma)
(pick ball90 rooma left)
(move rooma roomb)
(drop ball90 roomb left)
(move roomb rooma)
(pick ball900 rooma left)
(move rooma roomb)
(drop ball900 roomb left)
(move roomb rooma)
(pick ball901 rooma left)
(move rooma roomb)
(drop ball901 roomb left)
(move roomb rooma)
(pick ball902 rooma left)
(move rooma roomb)
(drop ball902 roomb left)
(move roomb rooma)
(pick ball903 rooma left)
(move rooma roomb)
(drop ball903 roomb left)
(move roomb rooma)
(pick ball904 rooma left)
(move rooma roomb)
(drop ball904 roomb left)
(move roomb rooma)
(pick ball905 rooma left)
(move rooma roomb)
(drop ball905 roomb left)
(move roomb rooma)
(pick ball906 rooma left)
(move rooma roomb)
(drop ball906 roomb left)
(move roomb rooma)
(pick ball907 rooma left)
(move rooma roomb)
(drop ball907 roomb left)
(move roomb rooma)
(pick ball908 rooma left)
(move rooma roomb)
(drop ball908 roomb left)
(move roomb rooma)
(pick ball909 rooma left)
(move rooma roomb)
(drop ball909 roomb left)
(move roomb rooma)
(pick ball91 rooma left)
(move rooma roomb)
(drop ball91 roomb left)
(move roomb rooma)
(pick ball910 rooma left)
(move rooma roomb)
(drop ball910 roomb left)
(move roomb rooma)
(pick ball911 rooma left)
(move rooma roomb)
(drop ball911 roomb left)
(move roomb rooma)
(pick ball912 rooma left)
(move rooma roomb)
(drop ball912 roomb left)
(move roomb rooma)
(pick ball913 rooma left)
(move rooma roomb)
(drop ball913 roomb left)
(move roomb rooma)
(pick ball914 rooma left)
(move rooma roomb)
(drop ball914 roomb left)
(move roomb rooma)
(pick ball915 rooma left)
(move rooma roomb)
(drop ball915 roomb left)
(move roomb rooma)
(pick ball916 rooma left)
(move rooma roomb)
(drop ball916 roomb left)
(move roomb rooma)
(pick ball917 rooma right)
(move rooma roomb)
(drop ball917 roomb right)
(move roomb rooma)
(pick ball918 rooma left)
(move rooma roomb)
(drop ball918 roomb left)
(move roomb rooma)
(pick ball919 rooma left)
(move rooma roomb)
(drop ball919 roomb left)
(move roomb rooma)
(pick ball92 rooma left)
(move rooma roomb)
(drop ball92 roomb left)
(move roomb rooma)
(pick ball920 rooma left)
(move rooma roomb)
(drop ball920 roomb left)
(move roomb rooma)
(pick ball921 rooma left)
(move rooma roomb)
(drop ball921 roomb left)
(move roomb rooma)
(pick ball922 rooma left)
(move rooma roomb)
(drop ball922 roomb left)
(move roomb rooma)
(pick ball923 rooma left)
(move rooma roomb)
(drop ball923 roomb left)
(move roomb rooma)
(pick ball924 rooma left)
(move rooma roomb)
(drop ball924 roomb left)
(move roomb rooma)
(pick ball925 rooma left)
(move rooma roomb)
(drop ball925 roomb left)
(move roomb rooma)
(pick ball926 rooma left)
(move rooma roomb)
(drop ball926 roomb left)
(move roomb rooma)
(pick ball927 rooma left)
(move rooma roomb)
(drop ball927 roomb left)
(move roomb rooma)
(pick ball928 rooma left)
(move rooma roomb)
(drop ball928 roomb left)
(move roomb rooma)
(pick ball929 rooma left)
(move rooma roomb)
(drop ball929 roomb left)
(move roomb rooma)
(pick ball93 rooma left)
(move rooma roomb)
(drop ball93 roomb left)
(move roomb rooma)
(pick ball930 rooma left)
(move rooma roomb)
(drop ball930 roomb left)
(move roomb rooma)
(pick ball931 rooma left)
(move rooma roomb)
(drop ball931 roomb left)
(move roomb rooma)
(pick ball932 rooma left)
(move rooma roomb)
(drop ball932 roomb left)
(move roomb rooma)
(pick ball933 rooma left)
(move rooma roomb)
(drop ball933 roomb left)
(move roomb rooma)
(pick ball934 rooma left)
(move rooma roomb)
(drop ball934 roomb left)
(move roomb rooma)
(pick ball935 rooma left)
(move rooma roomb)
(drop ball935 roomb left)
(move roomb rooma)
(pick ball936 rooma left)
(move rooma roomb)
(drop ball936 roomb left)
(move roomb rooma)
(pick ball937 rooma left)
(move rooma roomb)
(drop ball937 roomb left)
(move roomb rooma)
(pick ball938 rooma left)
(move rooma roomb)
(drop ball938 roomb left)
(move roomb rooma)
(pick ball939 rooma left)
(move rooma roomb)
(drop ball939 roomb left)
(move roomb rooma)
(pick ball94 rooma left)
(move rooma roomb)
(drop ball94 roomb left)
(move roomb rooma)
(pick ball940 rooma left)
(move rooma roomb)
(drop ball940 roomb left)
(move roomb rooma)
(pick ball941 rooma left)
(move rooma roomb)
(drop ball941 roomb left)
(move roomb rooma)
(pick ball942 rooma left)
(move rooma roomb)
(drop ball942 roomb left)
(move roomb rooma)
(pick ball943 rooma left)
(move rooma roomb)
(drop ball943 roomb left)
(move roomb rooma)
(pick ball944 rooma left)
(move rooma roomb)
(drop ball944 roomb left)
(move roomb rooma)
(pick ball945 rooma left)
(move rooma roomb)
(drop ball945 roomb left)
(move roomb rooma)
(pick ball946 rooma left)
(move rooma roomb)
(drop ball946 roomb left)
(move roomb rooma)
(pick ball947 rooma left)
(move rooma roomb)
(drop ball947 roomb left)
(move roomb rooma)
(pick ball948 rooma left)
(move rooma roomb)
(drop ball948 roomb left)
(move roomb rooma)
(pick ball949 rooma left)
(move rooma roomb)
(drop ball949 roomb left)
(move roomb rooma)
(pick ball95 rooma left)
(move rooma roomb)
(drop ball95 roomb left)
(move roomb rooma)
(pick ball950 rooma left)
(move rooma roomb)
(drop ball950 roomb left)
(move roomb rooma)
(pick ball951 rooma left)
(move rooma roomb)
(drop ball951 roomb left)
(move roomb rooma)
(pick ball952 rooma left)
(move rooma roomb)
(drop ball952 roomb left)
(move roomb rooma)
(pick ball953 rooma left)
(move rooma roomb)
(drop ball953 roomb left)
(move roomb rooma)
(pick ball954 rooma left)
(move rooma roomb)
(drop ball954 roomb left)
(move roomb rooma)
(pick ball955 rooma left)
(move rooma roomb)
(drop ball955 roomb left)
(move roomb rooma)
(pick ball956 rooma left)
(move rooma roomb)
(drop ball956 roomb left)
(move roomb rooma)
(pick ball957 rooma left)
(move rooma roomb)
(drop ball957 roomb left)
(move roomb rooma)
(pick ball958 rooma left)
(move rooma roomb)
(drop ball958 roomb left)
(move roomb rooma)
(pick ball959 rooma left)
(move rooma roomb)
(drop ball959 roomb left)
(move roomb rooma)
(pick ball96 rooma left)
(move rooma roomb)
(drop ball96 roomb left)
(move roomb rooma)
(pick ball960 rooma left)
(move rooma roomb)
(drop ball960 roomb left)
(move roomb rooma)
(pick ball961 rooma left)
(move rooma roomb)
(drop ball961 roomb left)
(move roomb rooma)
(pick ball962 rooma left)
(move rooma roomb)
(drop ball962 roomb left)
(move roomb rooma)
(pick ball963 rooma left)
(move rooma roomb)
(drop ball963 roomb left)
(move roomb rooma)
(pick ball964 rooma left)
(move rooma roomb)
(drop ball964 roomb left)
(move roomb rooma)
(pick ball965 rooma left)
(move rooma roomb)
(drop ball965 roomb left)
(move roomb rooma)
(pick ball966 rooma left)
(move rooma roomb)
(drop ball966 roomb left)
(move roomb rooma)
(pick ball967 rooma left)
(move rooma roomb)
(drop ball967 roomb left)
(move roomb rooma)
(pick ball968 rooma left)
(move rooma roomb)
(drop ball968 roomb left)
(move roomb rooma)
(pick ball969 rooma right)
(move rooma roomb)
(drop ball969 roomb right)
(move roomb rooma)
(pick ball97 rooma left)
(move rooma roomb)
(drop ball97 roomb left)
(move roomb rooma)
(pick ball970 rooma left)
(move rooma roomb)
(drop ball970 roomb left)
(move roomb rooma)
(pick ball971 rooma left)
(move rooma roomb)
(drop ball971 roomb left)
(move roomb rooma)
(pick ball972 rooma left)
(move rooma roomb)
(drop ball972 roomb left)
(move roomb rooma)
(pick ball973 rooma left)
(move rooma roomb)
(drop ball973 roomb left)
(move roomb rooma)
(pick ball974 rooma left)
(move rooma roomb)
(drop ball974 roomb left)
(move roomb rooma)
(pick ball975 rooma left)
(move rooma roomb)
(drop ball975 roomb left)
(move roomb rooma)
(pick ball976 rooma left)
(move rooma roomb)
(drop ball976 roomb left)
(move roomb rooma)
(pick ball977 rooma left)
(move rooma roomb)
(drop ball977 roomb left)
(move roomb rooma)
(pick ball978 rooma left)
(move rooma roomb)
(drop ball978 roomb left)
(move roomb rooma)
(pick ball979 rooma left)
(move rooma roomb)
(drop ball979 roomb left)
(move roomb rooma)
(pick ball98 rooma left)
(move rooma roomb)
(drop ball98 roomb left)
(move roomb rooma)
(pick ball980 rooma left)
(move rooma roomb)
(drop ball980 roomb left)
(move roomb rooma)
(pick ball981 rooma left)
(move rooma roomb)
(drop ball981 roomb left)
(move roomb rooma)
(pick ball982 rooma left)
(move rooma roomb)
(drop ball982 roomb left)
(move roomb rooma)
(pick ball983 rooma left)
(move rooma roomb)
(drop ball983 roomb left)
(move roomb rooma)
(pick ball984 rooma left)
(move rooma roomb)
(drop ball984 roomb left)
(move roomb rooma)
(pick ball985 rooma left)
(move rooma roomb)
(drop ball985 roomb left)
(move roomb rooma)
(pick ball986 rooma left)
(move rooma roomb)
(drop ball986 roomb left)
(move roomb rooma)
(pick ball987 rooma left)
(move rooma roomb)
(drop ball987 roomb left)
(move roomb rooma)
(pick ball988 rooma left)
(move rooma roomb)
(drop ball988 roomb left)
(move roomb rooma)
(pick ball989 rooma left)
(move rooma roomb)
(drop ball989 roomb left)
(move roomb rooma)
(pick ball99 rooma left)
(move rooma roomb)
(drop ball99 roomb left)
(move roomb rooma)
(pick ball990 rooma left)
(move rooma roomb)
(drop ball990 roomb left)
(move roomb rooma)
(pick ball991 rooma left)
(move rooma roomb)
(drop ball991 roomb left)
(move roomb rooma)
(pick ball992 rooma left)
(move rooma roomb)
(drop ball992 roomb left)
(move roomb rooma)
(pick ball993 rooma left)
(move rooma roomb)
(drop ball993 roomb left)
(move roomb rooma)
(pick ball994 rooma left)
(move rooma roomb)
(drop ball994 roomb left)
(move roomb rooma)
(pick ball995 rooma left)
(move rooma roomb)
(drop ball995 roomb left)
(move roomb rooma)
(pick ball996 rooma left)
(move rooma roomb)
(drop ball996 roomb left)
(move roomb rooma)
(pick ball997 rooma left)
(move rooma roomb)
(drop ball997 roomb left)
(move roomb rooma)
(pick ball998 rooma left)
(pick ball999 rooma right)
(move rooma roomb)
(drop ball998 roomb left)
(drop ball999 roomb right)
