(pick ball1 rooma left)
(move rooma roomb)
(drop ball1 roomb left)
(move roomb rooma)
(pick ball10 rooma left)
(move rooma roomb)
(drop ball10 roomb left)
(move roomb rooma)
(pick ball100 rooma left)
(move rooma roomb)
(drop ball100 roomb left)
(move roomb rooma)
(pick ball101 rooma left)
(move rooma roomb)
(drop ball101 roomb left)
(move roomb rooma)
(pick ball102 rooma left)
(move rooma roomb)
(drop ball102 roomb left)
(move roomb rooma)
(pick ball103 rooma left)
(move rooma roomb)
(drop ball103 roomb left)
(move roomb rooma)
(pick ball104 rooma left)
(move rooma roomb)
(drop ball104 roomb left)
(move roomb rooma)
(pick ball105 rooma left)
(move rooma roomb)
(drop ball105 roomb left)
(move roomb rooma)
(pick ball11 rooma left)
(move rooma roomb)
(drop ball11 roomb left)
(move roomb rooma)
(pick ball12 rooma left)
(move rooma roomb)
(drop ball12 roomb left)
(move roomb rooma)
(pick ball13 rooma left)
(move rooma roomb)
(drop ball13 roomb left)
(move roomb rooma)
(pick ball14 rooma left)
(move rooma roomb)
(drop ball14 roomb left)
(move roomb rooma)
(pick ball15 rooma left)
(move rooma roomb)
(drop ball15 roomb left)
(move roomb rooma)
(pick ball16 rooma left)
(move rooma roomb)
(drop ball16 roomb left)
(move roomb rooma)
(pick ball17 rooma left)
(move rooma roomb)
(drop ball17 roomb left)
(move roomb rooma)
(pick ball18 rooma left)
(move rooma roomb)
(drop ball18 roomb left)
(move roomb rooma)
(pick ball19 rooma left)
(move rooma roomb)
(drop ball19 roomb left)
(move roomb rooma)
(pick ball2 rooma left)
(move rooma roomb)
(drop ball2 roomb left)
(move roomb rooma)
(pick ball20 rooma left)
(move rooma roomb)
(drop ball20 roomb left)
(move roomb rooma)
(pick ball21 rooma left)
(move rooma roomb)
(drop ball21 roomb left)
(move roomb rooma)
(pick ball22 rooma left)
(move rooma roomb)
(drop ball22 roomb left)
(move roomb rooma)
(pick ball23 rooma left)
(move rooma roomb)
(drop ball23 roomb left)
(move roomb rooma)
(pick ball24 rooma left)
(move rooma roomb)
(drop ball24 roomb left)
(move roomb rooma)
(pick ball25 rooma left)
(move rooma roomb)
(drop ball25 roomb left)
(move roomb rooma)
(pick ball26 rooma left)
(move rooma roomb)
(drop ball26 roomb left)
(move roomb rooma)
(pick ball27 rooma left)
(move rooma roomb)
(drop ball27 roomb left)
(move roomb rooma)
(pick ball28 rooma left)
(move rooma roomb)
(drop ball28 roomb left)
(move roomb rooma)
(pick ball29 rooma left)
(move rooma roomb)
(drop ball29 roomb left)
(move roomb rooma)
(pick ball3 rooma left)
(move rooma roomb)
(drop ball3 roomb left)
(move roomb rooma)
(pick ball30 rooma left)
(move rooma roomb)
(drop ball30 roomb left)
(move roomb rooma)
(pick ball31 rooma left)
(move rooma roomb)
(drop ball31 roomb left)
(move roomb rooma)
(pick ball32 rooma left)
(move rooma roomb)
(drop ball32 roomb left)
(move roomb rooma)
(pick ball33 rooma left)
(move rooma roomb)
(drop ball33 roomb left)
(move roomb rooma)
(pick ball34 rooma left)
(move rooma roomb)
(drop ball34 roomb left)
(move roomb rooma)
(pick ball35 rooma left)
(move rooma roomb)
(drop ball35 roomb left)
(move roomb rooma)
(pick ball36 rooma left)
(move rooma roomb)
(drop ball36 roomb left)
(move roomb rooma)
(pick ball37 rooma left)
(move rooma roomb)
(drop ball37 roomb left)
(move roomb rooma)
(pick ball38 rooma left)
(move rooma roomb)
(drop ball38 roomb left)
(move roomb rooma)
(pick ball39 rooma left)
(move rooma roomb)
(drop ball39 roomb left)
(move roomb rooma)
(pick ball4 rooma left)
(move rooma roomb)
(drop ball4 roomb left)
(move roomb rooma)
(pick ball40 rooma left)
(move rooma roomb)
(drop ball40 roomb left)
(move roomb rooma)
(pick ball41 rooma left)
(move rooma roomb)
(drop ball41 roomb left)
(move roomb rooma)
(pick ball42 rooma left)
(move rooma roomb)
(drop ball42 roomb left)
(move roomb rooma)
(pick ball43 rooma left)
(move rooma roomb)
(drop ball43 roomb left)
(move roomb rooma)
(pick ball44 rooma left)
(move rooma roomb)
(drop ball44 roomb left)
(move roomb rooma)
(pick ball45 rooma left)
(move rooma roomb)
(drop ball45 roomb left)
(move roomb rooma)
(pick ball46 rooma left)
(move rooma roomb)
(drop ball46 roomb left)
(move roomb rooma)
(pick ball47 rooma left)
(move rooma roomb)
(drop ball47 roomb left)
(move roomb rooma)
(pick ball48 rooma left)
(move rooma roomb)
(drop ball48 roomb left)
(move roomb rooma)
(pick ball49 rooma left)
(move rooma roomb)
(drop ball49 roomb left)
(move roomb rooma)
(pick ball5 rooma left)
(move rooma roomb)
(drop ball5 roomb left)
(move roomb rooma)
(pick ball50 rooma left)
(move rooma roomb)
(drop ball50 roomb left)
(move roomb rooma)
(pick ball51 rooma left)
(move rooma roomb)
(drop ball51 roomb left)
(move roomb rooma)
(pick ball52 rooma left)
(move rooma roomb)
(drop ball52 roomb left)
(move roomb rooma)
(pick ball53 rooma left)
(move rooma roomb)
(drop ball53 roomb left)
(move roomb rooma)
(pick ball54 rooma left)
(move rooma roomb)
(drop ball54 roomb left)
(move roomb rooma)
(pick ball55 rooma left)
(move rooma roomb)
(drop ball55 roomb left)
(move roomb rooma)
(pick ball56 rooma left)
(move rooma roomb)
(drop ball56 roomb left)
(move roomb rooma)
(pick ball57 rooma left)
(move rooma roomb)
(drop ball57 roomb left)
(move roomb rooma)
(pick ball58 rooma left)
(move rooma roomb)
(drop ball58 roomb left)
(move roomb rooma)
(pick ball59 rooma left)
(move rooma roomb)
(drop ball59 roomb left)
(move roomb rooma)
(pick ball6 rooma left)
(move rooma roomb)
(drop ball6 roomb left)
(move roomb rooma)
(pick ball60 rooma left)
(move rooma roomb)
(drop ball60 roomb left)
(move roomb rooma)
(pick ball61 rooma right)
(move rooma roomb)
(drop ball61 roomb right)
(move roomb rooma)
(pick ball62 rooma left)
(move rooma roomb)
(drop ball62 roomb left)
(move roomb rooma)
(pick ball63 rooma left)
(move rooma roomb)
(drop ball63 roomb left)
(move roomb rooma)
(pick ball64 rooma left)
(move rooma roomb)
(drop ball64 roomb left)
(move roomb rooma)
(pick ball65 rooma left)
(move rooma roomb)
(drop ball65 roomb left)
(move roomb rooma)
(pick ball66 rooma left)
(move rooma roomb)
(drop ball66 roomb left)
(move roomb rooma)
(pick ball67 rooma left)
(move rooma roomb)
(drop ball67 roomb left)
(move roomb rooma)
(pick ball68 rooma right)
(move rooma roomb)
(drop ball68 roomb right)
(move roomb rooma)
(pick ball69 rooma left)
(move rooma roomb)
(drop ball69 roomb left)
(move roomb rooma)
(pick ball7 rooma left)
(move rooma roomb)
(drop ball7 roomb left)
(move roomb rooma)
(pick ball70 rooma left)
(move rooma roomb)
(drop ball70 roomb left)
(move roomb rooma)
(pick ball71 rooma left)
(move rooma roomb)
(drop ball71 roomb left)
(move roomb rooma)
(pick ball72 rooma left)
(move rooma roomb)
(drop ball72 roomb left)
(move roomb rooma)
(pick ball73 rooma left)
(move rooma roomb)
(drop ball73 roomb left)
(move roomb rooma)
(pick ball74 rooma left)
(move rooma roomb)
(drop ball74 roomb left)
(move roomb rooma)
(pick ball75 rooma left)
(move rooma roomb)
(drop ball75 roomb left)
(move roomb rooma)
(pick ball76 rooma left)
(move rooma roomb)
(drop ball76 roomb left)
(move roomb rooma)
(pick ball77 rooma left)
(move rooma roomb)
(drop ball77 roomb left)
(move roomb rooma)
(pick ball78 rooma left)
(move rooma roomb)
(drop ball78 roomb left)
(move roomb rooma)
(pick ball79 rooma left)
(move rooma roomb)
(drop ball79 roomb left)
(move roomb rooma)
(pick ball8 rooma left)
(move rooma roomb)
(drop ball8 roomb left)
(move roomb rooma)
(pick ball80 rooma left)
(move rooma roomb)
(drop ball80 roomb left)
(move roomb rooma)
(pick ball81 rooma left)
(move rooma roomb)
(drop ball81 roomb left)
(move roomb rooma)
(pick ball82 rooma left)
(move rooma roomb)
(drop ball82 roomb left)
(move roomb rooma)
(pick ball83 rooma left)
(move rooma roomb)
(drop ball83 roomb left)
(move roomb rooma)
(pick ball84 rooma left)
(move rooma roomb)
(drop ball84 roomb left)
(move roomb rooma)
(pick ball85 rooma left)
(move rooma roomb)
(drop ball85 roomb left)
(move roomb rooma)
(pick ball86 rooma left)
(move rooma roomb)
(drop ball86 roomb left)
(move roomb rooma)
(pick ball87 rooma left)
(move rooma roomb)
(drop ball87 roomb left)
(move roomb rooma)
(pick ball88 rooma left)
(move rooma roomb)
(drop ball88 roomb left)
(move roomb rooma)
(pick ball89 rooma left)
(move rooma roomb)
(drop ball89 roomb left)
(move roomb rooma)
(pick ball9 rooma left)
(move rooma roomb)
(drop ball9 roomb left)
(move roomb rooma)
(pick ball90 rooma left)
(move rooma roomb)
(drop ball90 roomb left)
(move roomb rooma)
(pick ball91 rooma left)
(move rooma roomb)
(drop ball91 roomb left)
(move roomb rooma)
(pick ball92 rooma left)
(move rooma roomb)
(drop ball92 roomb left)
(move roomb rooma)
(pick ball93 rooma left)
(move rooma roomb)
(drop ball93 roomb left)
(move roomb rooma)
(pick ball94 rooma left)
(move rooma roomb)
(drop ball94 roomb left)
(move roomb rooma)
(pick ball95 rooma left)
(move rooma roomb)
(drop ball95 roomb left)
(move roomb rooma)
(pick ball96 rooma left)
(move rooma roomb)
(drop ball96 roomb left)
(move roomb rooma)
(pick ball97 rooma left)
(move rooma roomb)
(drop ball97 roomb left)
(move roomb rooma)
(pick ball98 rooma left)
(pick ball99 rooma right)
(move rooma roomb)
(drop ball98 roomb left)
(drop ball99 roomb right)
